---
<div align="center">

# **REGRESIÓN LINEAL CON PYTHON - SKLEARN**

<div align="center">
  <img src="img/logo_uptc2.jpg" width="120">
</div>

**Profesor:** Duván Cataño  

**Curso:** Estadística para Analítica de Datos 

**Universidad Pedagógica y Tecnológica de Colombia**
</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Definición**


La regresión lineal es un modelo estadístico que describe la relación entre una variable dependiente $y$ y un conjunto de variables independientes 
$$X = (x_1, x_2, \dots, x_p).$$

El modelo se define como:

$$
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_p x_p + \varepsilon
$$

donde:

- $\beta_0$ es el intercepto
- $\beta_i$ son los coeficientes del modelo, para  $i=1, \ldots , p.$
- $\varepsilon$ es el término de error aleatorio

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Estimación por Mínimos Cuadrados Ordinarios (OLS)**

El objetivo es estimar los parámetros $\beta$ minimizando la suma de los errores al cuadrado:

$$
\min_{\beta} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2
$$

En forma matricial:

$$
\min_{\beta} (y - X\beta)^T (y - X\beta)
$$

La solución analítica es:

$$
\hat{\beta} = (X^T X)^{-1} X^T y
$$

Siempre que $X^T X$ sea invertible.

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">

### **Interpretación del Modelo**

Los principales elementos que hay que interpretar en un modelo de regresión lineal son los coeficientes de los predictores:


- $\beta_0$ : Es el **Intercepto**, corresponde al valor esperado de la variable respuesta $y$ cuando todos los predictores son cero.
    
- $\beta_j$ : Son los **Coeficientes** de regresión parcial de cada predictor, los cuales indican el cambio promedio esperado de la variable respuesta $y$ al incrementar en una unidad de la variable predictora $x_j$, manteniéndose constantes el resto de variables.

- La magnitud de cada coeficiente parcial de regresión depende de las unidades en las que se mida la variable predictora a la que corresponde, por lo que su magnitud no está asociada con la importancia de cada predictor.

- Para poder determinar qué impacto tienen en el modelo cada una de las variables, se emplean los coeficientes parciales estandarizados, que se obtienen al estandarizar (sustraer la media y dividir entre la desviación estándar) las variables predictoras previo ajuste del modelo. En este caso, $\beta_0$ se corresponde con el valor esperado de la variable respuesta cuando todos los predictores se encuentran en su valor promedio, y $\beta_j$ el cambio promedio esperado de la variable respuesta al incrementar en una desviación estándar la variable predictora $x_j$, manteniéndose constantes el resto de variables.

- Si bien los coeficientes de regresión suelen ser el primer objetivo de la interpretación de un modelo lineal, existen muchos otros aspectos (significancia del modelo en su conjunto, significancia de los predictores, condición de normalidad). **Éstos últimos suelen ser tratados con poco detalle cuando el único objetivo del modelo es realizar predicciones**, sin embargo, son muy relevantes si se quiere realizar inferencia, es decir, explicar las relaciones entre los predictores y la variable respuesta.

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Enfoque de Machine Learning**

Desde la perspectiva de Machine Learning, la regresión lineal se utiliza como un modelo predictivo.

El objetivo principal es minimizar el **Error de Predicción**:

$$
\mathcal{L}(\beta) = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2
$$

Se prioriza:

- Capacidad predictiva

- Generalización

- Escalabilidad computacional

</div>

---
---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Enfoque Estadístico**

Desde la perspectiva estadística, el interés se centra en la inferencia sobre los parámetros.

Se estudia la distribución de:

$$
\hat{\beta} \sim \mathcal{N}(\beta, \sigma^2 (X^T X)^{-1})
$$

Esto permite construir:

- Intervalos de confianza

- Pruebas de hipótesis

- Estadísticos $t$ y $F$

- Matriz de Información

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Supuestos del Modelo Lineal**

- **Linealidad:** La relación entre $X$ y $y$ es lineal.

- **Erroes:** Independencia de los errores.

- **Homocedasticidad:** Varianza constante del error.

- **Normalidad del error:** $\varepsilon \sim \mathcal{N}(0, \sigma^2)$.

- **Colinealidad:** No multicolinealidad perfecta.

</div>



---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Varianza del Estimador**

La matriz de varianza-covarianza es:

$$
\text{Var}(\hat{\beta}) = \sigma^2 (X^T X)^{-1}
$$

donde $\sigma^2$ se estima como:

$$
\hat{\sigma}^2 = \frac{1}{n - p - 1} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2
$$

</div>

---
---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Coeficiente de Determinación**

El coeficiente $R^2$ mide la proporción de la variabilidad explicada por el modelo:

$$ R^2 = 1 - \frac{\sum (y_i - \hat{y}_i)^2}{\sum (y_i - \bar{y})^2} $$

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Diferencia Conceptual**

Existen dos enfoques principales:

- **Enfoque predictivo**: centrado en minimizar el error de predicción

- **Enfoque inferencial**: centrado en analizar y validar los parámetros

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Comparación Conceptual**


- **Predicción:**
$$
\hat{y} = X \hat{\beta}
$$

- **Inferencia:**
$$
H_0: \beta_j = 0
$$

- **Estadístico de prueba:**
$$
t = \frac{\hat{\beta}_j}{SE(\hat{\beta}_j)}
$$

---

La regresión lineal es un modelo fundamental que puede ser interpretado desde dos perspectivas:


- Optimización numérica para predicción

- Modelo probabilístico para inferencia


Ambos enfoques comparten la misma base matemática, pero difieren en su propósito y uso práctico.

</div>

---


<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

<div align="center">

| Característica        | Scikit-Learn     | Statsmodels |
| --------------------- | ---------------- | ----------- |
| Enfoque               | Machine Learning | Estadístico |
| Predicción            | ✅ Excelente      | ✅ Buena     |
| Inferencia (p-values) | ❌ No             | ✅ Sí        |
| Facilidad de uso      | ✅ Muy alta       | Media       |
| Pipeline ML           | ✅ Sí             | ❌ No        |
| Interpretabilidad     | Básica           | Avanzada    |

</div>

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Significado "Lineal"**

El término "**Lineal**" en los modelos de regresión hace referencia al hecho de que los parámetros se incorporan en la ecuación de forma lineal, no a que necesariamente la relación entre cada predictor y la variable respuesta tenga que seguir un patrón lineal.

La siguiente ecuación muestra un modelo lineal en el que el predictor $x_1$ no es lineal respecto a $y$:


$$y = \beta_0 + \beta_1 x_1 + \beta_2 \log(x_1) + \epsilon$$

</div>

<p align="center">
   <img src="img/noline.png" width="600" height="300">
</p>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Bondad de ajuste del modelo**

Una vez ajustado el modelo, es necesario verificar su utilidad ya que, aún siendo la línea que mejor se ajusta a las observaciones entre todas las posibles, puede tener errores significativos. Las métricas más utilizadas para medir la calidad del ajuste son: el *Error Estándar de los Residuos* y el *Coeficiente de Determinación* $R^2.$

---

### **Error Estándar de los Residuos (Residual Standard Error, RSE)**

Mide la desviación promedio de cualquier punto estimado por el modelo respecto de la recta de regresión. Tiene las mismas unidades que la variable respuesta. Una forma de saber si el valor del $RSE$ es elevado consiste en dividirlo entre el valor medio de la variable respuesta, obteniendo así un % de la desviación.

$$RSE = \sqrt{\frac{1}{n - p - 1} RSS}$$

En modelos lineales simples, dado que hay un único predictor ($n - p - 1 = n - 2$).

---

### **Coeficiente de Determinación $R^2$**

Describe la proporción de varianza de la variable respuesta explicada por el modelo y relativa a la varianza total. Su valor está acotado entre 0 y 1. Al ser adimensional, presenta la ventaja frente al $RSE$ de ser más fácil de interpretar.

$$R^2 = \frac{\text{Suma de cuadrados totales - Suma de cuadrados residuales}}{\text{Suma de cuadrados totales}}$$

$$R^2 = 1 - \frac{\text{Suma de cuadrados residuales}}{\text{Suma de cuadrados totales}}$$

$$R^2 = 1 - \frac{\sum (\hat{y}_i - y_i)^2}{\sum (y_i - \bar{y})^2}$$

- En los modelos de *Regresión Lineal Simple* el valor de $R^2$ se corresponde con el **cuadrado del Coeficiente de Correlación de Pearson ($r$)** entre $x$ e $y$, no siendo así en Regresión Múltiple.

- En los Modelos Lineales Múltiples, cuantos más predictores se incluyan en el modelo, mayor es el valor de $R^2$. Esto es así ya que, por poco que sea, cada predictor va a explicar una parte de la variabilidad observada en $y$. Es por esto que $R^2$ no puede utilizarse para comparar modelos con distinto número de predictores.


- $R^2_{\text{ajustado}}$ introduce una penalización al valor de $R^2$ por cada predictor que se añade al modelo. El valor de la penalización depende del número de predictores utilizados y del tamaño de la muestra, es decir, del número de grados de libertad. Cuanto mayor es el tamaño de la muestra, más predictores se pueden incorporar en el modelo. 

- $R^2_{\text{ajustado}}$ permite encontrar el mejor modelo, aquel que consigue explicar mejor la variabilidad de $y$ con el menor número de predictores.

$$R^2_{\text{ajustado}} = 1 - \frac{SSE}{SST} \cdot \frac{n - 1}{n - p - 1} = R^2 - (1 - R^2) \cdot \frac{n - 1}{n - p - 1} = 1 - \frac{SSE / df_e}{SST / df_t}$$

- Siendo $SSE$ la variabilidad explicada por el modelo (Sum of Squares Explained), $SST$ la variabilidad total de $y$ (Sum of Squares Total), $n$ el tamaño de la muestra y $p$ el número de predictores introducidos en el modelo.

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Métricas de Desempeño**

1. **Mean Absolute Error (MAE):** Mide el error promedio absoluto entre los valores reales y predichos.

$$ MAE = \frac{1}{n} \sum_{i=1}^{n} |y_i - \hat{y}_i| $$

**Interpretación**

- Está en las mismas unidades de la variable objetivo

- Penaliza todos los errores de forma lineal

---

2. **Root Mean Squared Error (RMSE):** Mide la raíz del promedio de los errores al cuadrado.

$$ RMSE = \sqrt{ \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 }$$

**Interpretación**

- Penaliza más los errores grandes

- Está en las mismas unidades que la variable objetivo

---

3. **Mean Absolute Percentage Error (MAPE):** Mide el error promedio en términos porcentuales.

$$ MAPE = \frac{1}{n} \sum_{i=1}^{n} \left| \frac{y_i - \hat{y}_i}{y_i} \right| $$

**Interpretación**

Se interpreta como porcentaje:

$$ MAPE = 0.10 \Rightarrow 10\% \text{ de error promedio} $$

</div>

---

### **Tabla Comparativa**

<div align="center">

| Métrica | Sensibilidad a outliers | Interpretación | Escala       |
|---------|-------------------------|----------------|--------------|
| MAE     | Baja                    | Fácil          | Original     |
| RMSE    | Alta                    | Media          | Original     |
| MAPE    | Media                   | Muy fácil (%)  | Relativa     |
| R²      | —                       | Global         | Adimensional |

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">

### **Validación Cruzada (Cross-validation)**

La validación cruzada es un método estadístico utilizado para estimar la capacidad de los modelos de aprendizaje automático (machine learning). Se utiliza principalmente en el aprendizaje automático aplicado para estimar el desempeño de un algoritmo con datos no vistos previamente. La validación cruzada consiste en particionar un conjunto de datos en un grupo de entrenamiento y un grupo de prueba múltiples veces, para asegurar que el desempeño del modelo se evalúe de manera precisa.


**¿Por qué utilizar Validación Cruzada?**

La validación cruzada es crucial porque asegura que nuestro modelo no solo esté memorizando los datos de entrenamiento, sino que esté generalizando correctamente hacia datos nuevos. Este proceso ayuda a:

- Reducir el sobreajuste (overfitting) y el subajuste (underfitting).

- Proporcionar una estimación más precisa del desempeño del modelo.

- Garantizar que el modelo sea robusto y confiable.

</div>

<p align="center">
   <img src="img/CV3.png" width="900" height="500">
</p>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">

### **Método Tradicional vs Validación Cruzada**

El Método Tradicional (Train/Test Split) es como realizar un único examen final: divides tus datos una sola vez y confías en que esa partición sea representativa, lo cual es rápido pero riesgoso, ya que un "golpe de suerte" o una mala selección de datos puede sesgar los resultados. Por el contrario, la Validación Cruzada funciona como una serie de evaluaciones continuas; al rotar los datos de entrenamiento y prueba en múltiples iteraciones ($k$-folds), el modelo se enfrenta a todos los datos posibles. Esto reduce drásticamente el riesgo de sobreajuste y proporciona una métrica de error mucho más robusta y realista, asegurando que el modelo realmente haya aprendido a generalizar y no solo a memorizar un fragmento específico de la información.

<p align="center">
   <img src="img/CV4.png" width="900" height="500">
</p>

 </div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">

<h1 align="center"><b>Modelación con Regresión - Colombia Housing</b></h1> 

</div>

---

In [1]:
# ============ #
# 1. LIBRERÍAS #
# ============ #

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import plotly.graph_objects as go
import plotly.express as px

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_percentage_error

In [2]:
# =================== #
# 2. LECTURA DE RUTAS #
# =================== #

mainpath= "/Users/duvancatano/Documents/Estadistica_Analitica_Datos_UPTC_2026-2/data/housing"
filename= "housing_dataset.csv"
fullpath= os.path.join(mainpath,filename)

In [3]:
# ================= #
# 3. CARGA DE DATOS #
# ================= #

data = pd.read_csv(fullpath, sep=",") # El separador es "," porque en el archivo .csv los valores están separados por coma
pd.set_option('display.max_columns', None) # Para mostrar todas las columnas del DataFrame sin truncar

In [4]:
data.sample(20)

,departamento,municipio,zona_urbana_rural,tipo_de_vivienda,tenencia_de_la_vivienda,area_total_m2,habitaciones,banos,pisos,antiguedad_de_la_vivienda,calidad_de_construccion,parqueaderos,estrato,tamano_del_hogar,numero_de_ninos,numero_de_adultos_mayores,genero_del_jefe_del_hogar,edad_del_jefe_del_hogar,nivel_educativo_del_jefe_del_hogar,situacion_laboral_del_jefe_del_hogar,distancia_al_centro_de_la_ciudad_km,indice_de_seguridad_del_barrio,acceso_a_transporte_publico,acceso_a_internet,acceso_a_agua_potable,acceso_a_gas,indice_de_pobreza,acceso_a_credito,ahorros_del_hogar,ingreso_del_hogar,valor_de_mercado_de_la_vivienda
3648,Antioquia,Cartagena,Urban,Apartment,Family,59.767582,5,1,3,53,Low,0,5,2,1,2,Female,62,Primary,Informal,15.508372,49.987585,Yes,Yes,Yes,Yes,0.453390,No,2.334562e+06,6.508401e+06,94.200600
4965,Bolívar,Cali,Urban,Apartment,Owned,117.931180,2,1,1,55,Medium,2,4,1,1,1,Male,59,Secondary,Unemployed,14.379057,84.517254,Yes,Yes,Yes,Yes,0.703930,Yes,8.265276e+05,2.595448e+06,136.952229
2721,Santander,Medellín,Urban,House,Owned,49.802472,5,3,1,67,Medium,2,1,3,3,1,Male,55,Secondary,Formal,3.233137,43.237412,Yes,Yes,Yes,Yes,0.490319,Yes,1.079425e+06,1.261635e+06,58.953182
134,Risaralda,Barranquilla,Urban,Apartment,Owned,72.111981,1,1,2,5,Medium,1,4,5,0,0,Male,28,Secondary,Unemployed,7.024021,44.956388,Yes,Yes,Yes,Yes,0.177262,No,1.455555e+06,2.157165e+06,79.461699
8644,Antioquia,Bogotá,Rural,House,Rented,120.262856,1,2,1,3,High,1,4,7,0,1,Male,25,University,Formal,23.707768,89.773675,Yes,Yes,Yes,No,0.267677,No,2.171242e+06,1.134849e+07,130.037334
2125,Bolívar,Cartagena,Rural,Farm,Rented,130.823174,5,3,3,69,Medium,0,3,6,2,1,Male,49,University,Formal,4.250086,86.668070,Yes,Yes,Yes,Yes,0.267632,Yes,5.540710e+06,8.289487e+06,112.775393
1624,Bolívar,Pereira,Urban,Farm,Rented,97.456598,2,2,3,50,Low,2,2,1,1,1,Female,60,University,Formal,15.340054,76.319418,Yes,Yes,Yes,Yes,0.025560,Yes,3.419473e+05,5.426537e+06,96.053555
3916,Atlántico,Pereira,Rural,Farm,Owned,162.843256,4,2,1,5,Medium,0,3,3,1,2,Male,74,Secondary,Formal,5.729534,96.122892,Yes,Yes,Yes,Yes,0.323064,Yes,1.038973e+06,5.413254e+06,160.151200
1868,Santander,Cali,Urban,Apartment,Rented,136.465139,2,2,2,43,Medium,2,2,3,2,0,Male,53,Secondary,Formal,15.183461,41.153076,Yes,Yes,Yes,Yes,0.111862,No,4.482838e+06,3.465162e+06,150.395951
9380,Bolívar,Medellín,Urban,Apartment,Owned,89.076319,1,2,2,44,Medium,2,4,1,1,1,Male,70,University,Formal,2.489456,58.412388,Yes,Yes,Yes,Yes,0.145108,Yes,1.052508e+06,8.897959e+06,82.784838
3677,Cundinamarca,Cali,Rural,Apartment,Owned,19.512107,5,1,2,39,Medium,0,3,7,1,2,Female,75,Secondary,Informal,4.390315,56.172566,Yes,Yes,Yes,Yes,0.396846,No,9.245655e+05,4.315603e+06,56.018084
2648,Risaralda,Cartagena,Urban,Apartment,Owned,42.797250,5,1,1,39,Low,1,3,7,4,0,Female,50,Secondary,Formal,3.827314,67.716942,Yes,Yes,Yes,Yes,0.496022,Yes,2.447171e+06,7.249143e+06,91.272358
3889,Atlántico,Medellín,Urban,House,Family,290.090527,4,3,2,18,Medium,0,5,3,0,2,Male,42,University,Formal,2.717928,47.056569,Yes,Yes,Yes,Yes,0.344657,No,6.482432e+06,1.481205e+07,218.471725
2789,Atlántico,Barranquilla,Urban,Farm,Family,176.615945,1,3,1,6,Medium,0,2,4,1,0,Female,51,Secondary,Formal,12.118563,79.577194,Yes,Yes,Yes,Yes,0.288982,No,1.579720e+06,4.014147e+06,144.039994
4736,Risaralda,Bucaramanga,Urban,House,Owned,34.095900,2,2,1,25,High,2,4,6,1,1,Female,56,Primary,Formal,8.557045,56.430742,Yes,Yes,Yes,Yes,0.235523,Yes,1.671416e+06,6.111431e+06,79.001085
404,Caldas,Bogotá,Rural,Apartment,Family,108.733103,3,2,3,19,Medium,2,1,4,0,1,Male,65,Primary,Informal,3.442592,33.740254,Yes,Yes,Yes,Yes,0.210776,No,1.274493e+06,1.296394e+06,105.965225
9912,Atlántico,Bogotá,Urban,Apartment,Family,73.664228,4,2,3,54,Medium,2,1,1,1,0,Male,28,University,Unemployed,20.162675,53.998256,No,Yes,Yes,Yes,0.273420,No,2.326274e+06,1.889670e+05,63.980297
6396,Santander,Manizales,Urban,Farm,Family,47.086581,2,2,3,61,Medium,2,1,7,1,2,Male,64,Secondary,Informal,9.221597,83.217636,No,No,Yes,Yes,0.530220,Yes,3.531634e+06,1.324866e+06,18.494227
3589,Caldas,Pereira,Urban,House,Rented,54.571919,2,1,2,17,Low,2,2,4,3,1,Male,42,Secondary,Formal,9.755739,52.910226,No,Yes,Yes,Yes,0.257076,No,4.529006e+05,3.855520e+06,82.695870
1545,Atlántico,Cartagena,Urban,Farm,Owned,80.451645,5,2,3,44,Medium,1,1,4,1,0,Male,27,Secondary,Formal,7.165259,72.216577,Yes,Yes,Yes,Yes,0.726288,Yes,3.205165e+06,3.301067e+06,57.506960

In [5]:
# ========================= #
# 4. SELECCIÓN DE VARIABLES #
# ========================= #

df = data[[
 'municipio',
 'zona_urbana_rural',
 'tipo_de_vivienda',
 'area_total_m2',
 'habitaciones',
 'banos',
 'antiguedad_de_la_vivienda',
 'parqueaderos',
 'estrato',
 'distancia_al_centro_de_la_ciudad_km',
 'acceso_a_transporte_publico',
 'acceso_a_internet',
 'acceso_a_agua_potable',
 'acceso_a_gas',
 'ingreso_del_hogar',
 'valor_de_mercado_de_la_vivienda'
 ]]

In [6]:
# ============================== #
# 5. IDENTIFICACIÓN DE VARIABLES #
# ============================== #

cat_cols = [
    'municipio',
    'zona_urbana_rural',
    'tipo_de_vivienda',
    'acceso_a_transporte_publico',
    'acceso_a_internet',
    'acceso_a_agua_potable',
    'acceso_a_gas'
]

num_cols = [
    'area_total_m2',  
    'ingreso_del_hogar',
    'distancia_al_centro_de_la_ciudad_km'
]

int_cols = [
    'habitaciones', 
    'banos',
    'antiguedad_de_la_vivienda', 
    'parqueaderos',
    'estrato'
]

target = 'valor_de_mercado_de_la_vivienda'

In [7]:
# ================================================================================================================== #
# 4. ONE-HOT ENCODING (A las variables categóricas aplícales One-Hot Encoding, y a las numéricas déjalas como están) #
# ================================================================================================================== #
 
preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), cat_cols),
    ('num', StandardScaler(), num_cols + int_cols)
])

In [8]:
# =============================== #
# VISUALIZAR EL PRE-PROCESAMIENTO #
# =============================== #

preprocessor

ColumnTransformer(transformers=[('cat',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore'),
                                 ['municipio', 'zona_urbana_rural',
                                  'tipo_de_vivienda',
                                  'acceso_a_transporte_publico',
                                  'acceso_a_internet', 'acceso_a_agua_potable',
                                  'acceso_a_gas']),
                                ('num', StandardScaler(),
                                 ['area_total_m2', 'ingreso_del_hogar',
                                  'distancia_al_centro_de_la_ciudad_km',
                                  'habitaciones', 'banos',
                                  'antiguedad_de_la_vivienda', 'parqueaderos',
                                  'estrato'])])

In [9]:
# ============================= #
# 5. MOSTRAR LA BASE CODIFICADA #
# ============================= #
 
X = df[cat_cols + num_cols + int_cols]
X_encoded = preprocessor.fit_transform(X)
feature_names = preprocessor.get_feature_names_out()
X_encoded_df = pd.DataFrame(X_encoded, columns=feature_names)
X_encoded_df.sample(20)

,cat__municipio_Bogotá,cat__municipio_Bucaramanga,cat__municipio_Cali,cat__municipio_Cartagena,cat__municipio_Manizales,cat__municipio_Medellín,cat__municipio_Pereira,cat__zona_urbana_rural_Urban,cat__tipo_de_vivienda_Farm,cat__tipo_de_vivienda_House,cat__acceso_a_transporte_publico_Yes,cat__acceso_a_internet_Yes,cat__acceso_a_agua_potable_Yes,cat__acceso_a_gas_Yes,num__area_total_m2,num__ingreso_del_hogar,num__distancia_al_centro_de_la_ciudad_km,num__habitaciones,num__banos,num__antiguedad_de_la_vivienda,num__parqueaderos,num__estrato
8958,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,-0.921667,-0.762944,-0.963335,-0.003114,1.224726,1.255986,0.003064,-0.510692
3815,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,-0.135352,1.655663,-1.034376,1.412169,1.224726,0.664173,-1.222575,1.517205
3744,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.344100,-0.795088,0.476591,-0.003114,1.224726,0.713490,1.228704,0.165274
5300,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.505474,-0.568871,-0.780837,0.704528,1.224726,-1.555128,0.003064,-1.186658
2888,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,-1.098160,-0.452704,-0.924868,0.704528,0.003298,0.960079,-1.222575,-0.510692
8644,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.243957,1.455976,1.938417,-1.418396,0.003298,-1.555128,0.003064,0.841240
6065,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,-1.448784,-0.348520,0.508482,0.704528,-1.218130,-0.568772,1.228704,0.165274
6950,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,-0.318233,-0.748552,-0.739426,1.412169,-1.218130,-0.272865,1.228704,-0.510692
2091,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,-1.139149,-0.471224,-1.240734,1.412169,-1.218130,-0.568772,0.003064,0.841240
5309,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.349232,-0.828280,-0.511824,0.704528,0.003298,-0.815361,0.003064,-1.186658
5527,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,-0.392403,-0.874061,1.583960,1.412169,-1.218130,1.699846,-1.222575,-0.510692
3757,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,-0.965432,0.498957,-0.183436,0.704528,0.003298,1.650528,-1.222575,0.165274
8032,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,-0.930016,0.174999,-0.495569,-1.418396,-1.218130,-0.519454,1.228704,0.165274
8424,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.692005,2.134499,-0.992327,1.412169,0.003298,-1.407175,-1.222575,1.517205
8894,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.581888,-0.388357,2.456715,-1.418396,1.224726,0.664173,-1.222575,-0.510692
4158,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.670401,-0.731575,-0.574470,1.412169,0.003298,-1.308539,-1.222575,0.165274
4547,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,-0.049097,-0.036156,0.126045,1.412169,0.003298,0.170995,-1.222575,0.841240
6261,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.226236,-0.746405,-0.058706,-0.710755,0.003298,-1.505810,1.228704,-1.186658
2308,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.513163,-0.563623,1.178189,-0.003114,1.224726,1.108033,1.228704,-1.186658
1075,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,-0.468615,-0.794204,1.298785,-0.003114,-1.218130,0.269630,0.003064,-0.510692

In [10]:
# ============================================= #
# 6. MOSTRAR LAS COLUMNAS DE LA BASE CODIFICADA #
# ============================================= #
X_encoded_df.columns.tolist()

['cat__municipio_Bogotá',
 'cat__municipio_Bucaramanga',
 'cat__municipio_Cali',
 'cat__municipio_Cartagena',
 'cat__municipio_Manizales',
 'cat__municipio_Medellín',
 'cat__municipio_Pereira',
 'cat__zona_urbana_rural_Urban',
 'cat__tipo_de_vivienda_Farm',
 'cat__tipo_de_vivienda_House',
 'cat__acceso_a_transporte_publico_Yes',
 'cat__acceso_a_internet_Yes',
 'cat__acceso_a_agua_potable_Yes',
 'cat__acceso_a_gas_Yes',
 'num__area_total_m2',
 'num__ingreso_del_hogar',
 'num__distancia_al_centro_de_la_ciudad_km',
 'num__habitaciones',
 'num__banos',
 'num__antiguedad_de_la_vivienda',
 'num__parqueaderos',
 'num__estrato']

In [11]:
# ===================================================== #
# 7. ANÁLISIS DE CORRELACIÓN (Solo variables numéricas) #
# ===================================================== #

# MATRIZ DE CORRELACIÓN
corr = df[num_cols + int_cols + [target]].corr()

# MÁSCARA TRIANGULAR
mask = np.triu(
    np.ones_like(corr,dtype=bool)
)

corr_masked = corr.mask(mask)

# HEATMAP INTERACTIVO
fig = px.imshow(
    corr_masked,
    text_auto='.2f',
    color_continuous_scale='RdBu_r',
    zmin=-1,
    zmax=1,
    aspect='auto'
)

# HOVER PERSONALIZADO
fig.update_traces(
    hovertemplate=
    '<b>X</b>: %{x}<br>' +
    '<b>Y</b>: %{y}<br>' +
    '<b>Correlación</b>: %{z:.3f}<extra></extra>'
)

# LAYOUT
fig.update_layout(
    template='plotly_white',
    title={
        'text':'Matriz de Correlación',
        'x':0.5,
        'font':{'size':30}
    },
    width=1000,
    height=850,
    coloraxis_colorbar=dict(
        title='Correlación'
    )
)

fig.update_xaxes(
    tickangle=45,
    side='bottom'
)

fig.update_yaxes(
    autorange='reversed'
)

fig.show()

In [12]:
# ========================= #
# 8. PARTICIÓN TRAIN / TEST #
# ========================= #

X = df[cat_cols + num_cols + int_cols] 
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [13]:
# ====================== #
# 9. MODELO DE REGRESIÓN #
# ====================== #

model = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('regressor', LinearRegression())
])

model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['municipio',
                                                   'zona_urbana_rural',
                                                   'tipo_de_vivienda',
                                                   'acceso_a_transporte_publico',
                                                   'acceso_a_internet',
                                                   'acceso_a_agua_potable',
                                                   'acceso_a_gas']),
                                                 ('num', StandardScaler(),
                                                  ['area_total_m2',
                                                   'ingreso_del_hogar',
                                                   'distancia_al_centro_de_la_ciudad_km',
                                                   'habitaciones', 'banos',
                                                   'antiguedad_de_la_vivienda',
                                                   'parqueaderos',
                                                   'estrato'])])),
                ('regressor', LinearRegression())])

In [14]:
# ============== #
# 10. EVALUACIÓN #
# ============== #

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mape = mean_absolute_percentage_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

metricas = pd.DataFrame({

    "Métrica":[
        "MAE",
        "RMSE",
        "MAPE",
        "MAPE (%)",
        "R²"
    ],

    "Valor":[
        mae,
        rmse,
        mape,
        mape*100,
        r2
    ]

})

metricas["Valor"] = metricas["Valor"].round(4)
metricas

    Métrica    Valor
0       MAE  20.1440
1      RMSE  25.1767
2      MAPE   0.3557
3  MAPE (%)  35.5672
4        R²   0.7456

In [15]:
# ======================================== #
# 10.1. DATAFRAME CON RESULTADOS Y ERRORES # 
# ======================================== #

# Asegurar formatos
X_test_df = pd.DataFrame(X_test).reset_index(drop=True)
y_test_df = pd.Series(y_test).reset_index(drop=True)
y_pred_df = pd.Series(y_pred)

# Construir DataFrame final
df_resultados = X_test_df.copy()
df_resultados["y_real"] = y_test_df
df_resultados["y_pred"] = y_pred_df

df_resultados["error"] = df_resultados["y_real"] - df_resultados["y_pred"]
df_resultados["abs_error"] = df_resultados["error"].abs()

df_resultados.sample(20)

,municipio,zona_urbana_rural,tipo_de_vivienda,acceso_a_transporte_publico,acceso_a_internet,acceso_a_agua_potable,acceso_a_gas,area_total_m2,ingreso_del_hogar,distancia_al_centro_de_la_ciudad_km,habitaciones,banos,antiguedad_de_la_vivienda,parqueaderos,estrato,y_real,y_pred,error,abs_error
883,Bucaramanga,Urban,House,Yes,Yes,Yes,No,243.081769,3.075886e+06,9.518961,5,2,9,1,2,210.609767,190.293707,20.316059,20.316059
1111,Pereira,Urban,Farm,Yes,Yes,Yes,Yes,46.269221,7.622532e+06,1.532822,2,1,13,1,4,114.673612,98.187907,16.485705,16.485705
422,Pereira,Urban,House,Yes,No,Yes,Yes,137.385428,4.876565e+06,17.720489,4,2,29,0,4,154.542538,150.925882,3.616655,3.616655
826,Bucaramanga,Urban,Farm,No,Yes,Yes,Yes,101.216388,2.803506e+06,11.373852,3,1,21,2,1,121.410112,85.083829,36.326283,36.326283
63,Bogotá,Urban,Apartment,Yes,No,Yes,Yes,72.869074,1.539607e+06,15.400374,5,1,2,1,1,81.023645,71.910695,9.112950,9.112950
406,Bucaramanga,Urban,Farm,Yes,Yes,Yes,Yes,92.130981,1.575366e+07,4.731628,5,2,5,0,5,141.357221,143.666162,-2.308941,2.308941
1791,Pereira,Urban,House,No,Yes,Yes,Yes,121.541156,3.651171e+06,5.154267,5,1,2,0,3,168.946893,131.760673,37.186220,37.186220
198,Pereira,Urban,Farm,Yes,Yes,Yes,Yes,175.705413,1.739339e+06,2.262828,5,2,27,1,1,71.329123,129.328969,-57.999847,57.999847
950,Pereira,Urban,Apartment,Yes,Yes,Yes,Yes,75.625850,4.787416e+06,2.506592,1,1,66,2,3,52.263311,89.094717,-36.831406,36.831406
1151,Manizales,Urban,Farm,Yes,Yes,Yes,Yes,71.907211,3.345269e+06,0.367194,5,2,25,1,2,44.987281,81.476759,-36.489477,36.489477
673,Bogotá,Urban,Apartment,Yes,Yes,Yes,Yes,116.541626,1.545091e+07,7.539986,2,1,59,0,5,126.717479,145.936410,-19.218931,19.218931
540,Medellín,Rural,House,Yes,Yes,Yes,Yes,69.220203,1.588541e+07,13.972676,5,3,22,0,6,166.133219,141.884688,24.248532,24.248532
899,Manizales,Urban,Farm,No,No,Yes,Yes,182.947464,4.446279e+06,8.511334,1,2,51,1,3,146.029511,157.063193,-11.033682,11.033682
1435,Bogotá,Urban,Farm,Yes,Yes,Yes,Yes,100.026659,1.736347e+07,17.792973,2,2,4,2,4,135.221848,131.116212,4.105636,4.105636
321,Bucaramanga,Urban,House,Yes,Yes,Yes,Yes,165.681756,6.492297e+06,22.975295,3,3,41,0,3,124.574515,150.174025,-25.599510,25.599510
12,Cartagena,Urban,Farm,Yes,Yes,Yes,Yes,168.532017,3.548804e+06,28.386774,2,3,33,2,1,134.302464,122.185444,12.117020,12.117020
1296,Medellín,Urban,Farm,Yes,Yes,No,Yes,275.781613,2.676940e+06,2.689792,2,3,47,1,2,190.685270,200.280826,-9.595555,9.595555
426,Manizales,Urban,House,Yes,Yes,Yes,Yes,80.851437,4.374151e+06,7.226318,4,1,66,0,3,54.246018,93.973245,-39.727227,39.727227
1641,Cartagena,Urban,Apartment,Yes,Yes,No,Yes,220.283221,3.727047e+06,18.354010,3,2,46,1,3,178.246742,180.690194,-2.443452,2.443452
1822,Bogotá,Urban,House,Yes,Yes,Yes,Yes,27.050356,1.444459e+07,11.114356,2,1,29,1,5,110.006641,98.068989,11.937652,11.937652

In [16]:
# ====================== #
# 10.2. REAL VS PREDICHO #
# ====================== #
from scipy.stats import pearsonr

# CORRELACIÓN
r,p = pearsonr(
    df_resultados["y_real"],
    df_resultados["y_pred"]
)

# SCATTER INTERACTIVO
fig = px.scatter(
    df_resultados,
    x="y_real",
    y="y_pred",
    opacity=0.70,
    trendline="ols"
)

# LÍNEA IDEAL
min_val = min(
    df_resultados["y_real"].min(),
    df_resultados["y_pred"].min()
)

max_val = max(
    df_resultados["y_real"].max(),
    df_resultados["y_pred"].max()
)

fig.add_trace(

    go.Scatter(
        x=[min_val,max_val],
        y=[min_val,max_val],
        mode='lines',
        name='Predicción Perfecta',
        line=dict(
            dash='dash',
            width=3,
            color='black'
        ),
        hovertemplate=
        '<b>Línea Ideal</b><extra></extra>'
    )

)

#=====================================#
# LAYOUT
#=====================================#

fig.update_layout(
    template='plotly_white',
    title={
        'text':
        'Valores Reales vs Predicciones'
        f'<br><sup>Correlación Pearson = {r:.4f} | p-valor = {p:.6f}</sup>',
        'x':0.5,
        'font':{'size':28}
    },
    xaxis_title='Valores Reales',
    yaxis_title='Predicciones',
    width=1000,
    height=750,
    legend_title='Referencia'
)

#=====================================#
# HOVER
#=====================================#

fig.update_traces(
    selector=dict(mode='markers'),
    marker=dict(
        size=8,
        line=dict(width=1)
    ),
    hovertemplate=
    '<b>Valor Real</b>: %{x:.2f}<br>' +
    '<b>Predicción</b>: %{y:.2f}<extra></extra>'
)

fig.show()

In [17]:
# ============================= #
# 10.3. DISTRIBUCIÓN DE ERRORES #
# ============================= #
from scipy.stats import skew,kurtosis

# ESTADÍSTICAS DEL ERROR
media_error = df_resultados["error"].mean()
std_error = df_resultados["error"].std()
asimetria = skew(df_resultados["error"])
curtosis_error = kurtosis(df_resultados["error"])

# HISTOGRAMA INTERACTIVO
fig = px.histogram(
    df_resultados,
    x="error",
    nbins=30,
    marginal="box",
    opacity=0.80
)

# LÍNEA MEDIA
fig.add_vline(
    x=media_error,
    line_width=3,
    line_dash="dash",
    annotation_text=f"Media = {media_error:.2f}",
    annotation_position="top"
)

# CURVA KDE
fig.update_traces(
    hovertemplate=
    '<b>Error</b>: %{x:.2f}<br>' +
    '<b>Frecuencia</b>: %{y}<extra></extra>'
)

# LAYOUT
fig.update_layout(
    template='plotly_white',
    title={
        'text':
        'Distribución de Errores'
        f'<br><sup>Media = {media_error:.2f} | Desv = {std_error:.2f} | '
        f'Asimetría = {asimetria:.2f} | Curtosis = {curtosis_error:.2f}</sup>',
        'x':0.5,
        'font':{'size':28}
    },
    xaxis_title='Error',
    yaxis_title='Frecuencia',
    width=1100,
    height=700,
    bargap=0.05
)

fig.show()

In [18]:
# ====================== #
# 11. VALIDACIÓN CRUZADA #
# ====================== #

scoring = {
    'mae': 'neg_mean_absolute_error',
    'rmse': 'neg_root_mean_squared_error',
    'mape': 'neg_mean_absolute_percentage_error',
    'r2': 'r2'
}

cv_results = cross_validate(model, X, y, cv=10, scoring=scoring)

metricas_cv = pd.DataFrame({

    "Métrica":[
        "CV MAE",
        "CV RMSE",
        "CV MAPE",
        "CV R²",
        "FIT TIME",
        "SCORE TIME"
    ],

    "Valor":[
        -cv_results['test_mae'].mean(),
        -cv_results['test_rmse'].mean(),
        -cv_results['test_mape'].mean(),
        cv_results['test_r2'].mean(),
        cv_results['fit_time'].mean(),
        cv_results['score_time'].mean()
    ]
})

# REDONDEAR
metricas_cv["Valor"] = (
    metricas_cv["Valor"]
    .round(4)
)

# MOSTRAR
metricas_cv

      Métrica    Valor
0      CV MAE  19.8774
1     CV RMSE  24.9108
2     CV MAPE   0.3758
3       CV R²   0.7521
4    FIT TIME   0.0112
5  SCORE TIME   0.0028

In [19]:
# ========================== #
# RESULTADOS CRUDOS DE LA CV #
# ========================== #

(cv_results)

{'fit_time': array([0.01732492, 0.01299882, 0.01134896, 0.01127005, 0.01033807,
        0.01002002, 0.00972009, 0.0096879 , 0.01008701, 0.00941586]),
 'score_time': array([0.00384688, 0.00283694, 0.00325918, 0.00261998, 0.00246811,
        0.00270009, 0.0020709 , 0.00308514, 0.00233912, 0.00253105]),
 'test_mae': array([-19.28349999, -19.57467601, -20.67711924, -20.12844674,
        -20.08762551, -20.26246995, -19.09406329, -19.56548747,
        -19.44659153, -20.65371449]),
 'test_rmse': array([-24.31427241, -24.42813967, -25.54517707, -25.29960675,
        -24.83587123, -25.27157198, -24.41220838, -24.57895594,
        -24.71152156, -25.71108253]),
 'test_mape': array([-0.27547637, -0.4511907 , -0.36838395, -0.52497986, -0.32293712,
        -0.60214911, -0.27688411, -0.34030843, -0.28717578, -0.30897394]),
 'test_r2': array([0.76379165, 0.73944219, 0.74964748, 0.7520724 , 0.74734917,
        0.74486673, 0.75533724, 0.75882901, 0.76175715, 0.7479369 ])}

In [20]:
# ======================================= #
# VISUALIZACIÓN DE DENSIDADES POR MÉTRICA #
# ======================================= #

from plotly.subplots import make_subplots
from scipy.stats import gaussian_kde

cv_df = pd.DataFrame({
    'MAE': -cv_results['test_mae'],
    'RMSE': -cv_results['test_rmse'],
    'MAPE': -cv_results['test_mape'],
    'R2': cv_results['test_r2']
})

# SUBPLOTS 2x2
fig = make_subplots(
    rows=2,
    cols=2,
    subplot_titles=[
        'Distribución MAE',
        'Distribución RMSE',
        'Distribución MAPE',
        'Distribución R²'
    ],
    vertical_spacing=0.18,
    horizontal_spacing=0.12
)

metricas = ['MAE','RMSE','MAPE','R2']

# LOOP GRÁFICAS
for i,metrica in enumerate(metricas):

    fila = (i//2)+1
    columna = (i%2)+1

    valores = cv_df[metrica]

    # KDE
    x_grid = np.linspace(
        valores.min(),
        valores.max(),
        300
    )

    kde = gaussian_kde(valores)(x_grid)

    # CURVA KDE
    fig.add_trace(

        go.Scatter(
            x=x_grid,
            y=kde,
            mode='lines',
            fill='tozeroy',
            line=dict(width=3),
            hovertemplate=
            f'<b>{metrica}</b>: %{{x:.4f}}<br>' +
            '<b>Densidad</b>: %{y:.4f}<extra></extra>'
        ),

        row=fila,
        col=columna
    )

    # MEDIA
    media = valores.mean()

    fig.add_vline(
        x=media,
        line_dash='dash',
        line_width=2,
        row=fila,
        col=columna
    )

    # ANOTACIÓN
    fig.add_annotation(
        x=media,
        y=max(kde)*0.90,
        text=f'Media = {media:.4f}',
        showarrow=False,
        font=dict(size=11),
        bgcolor='white',
        row=fila,
        col=columna
    )

    # AUMENTAR RANGO EJE X
    xmin = valores.min()
    xmax = valores.max()

    rango = xmax - xmin

    padding = 0.15

    fig.update_xaxes(
        range=[
            xmin - padding*rango,
            xmax + padding*rango
        ],
        row=fila,
        col=columna
    )

# LAYOUT
fig.update_layout(
    template='plotly_white',
    title={
        'text':'Distribución de Métricas de Validación Cruzada',
        'x':0.5,
        'font':{'size':28}
    },
    width=1300,
    height=900,
    showlegend=False
)

# TÍTULOS SUBPLOTS
fig.update_annotations(
    font_size=16
)

# EJES
fig.update_xaxes(
    showgrid=True
)

fig.update_yaxes(
    showgrid=True
)

# MOSTRAR
fig.show()

In [21]:
# ================================================== #
# 12. IMPORTANCIA DE VARIABLES MEDIANTE COEFICIENTES #
# ================================================== #

feature_names = model.named_steps['preprocessing'].get_feature_names_out()
coefficients = model.named_steps['regressor'].coef_

importance = pd.Series(coefficients, index=feature_names)
importance = importance.sort_values(key=abs, ascending=False)

print(importance.head(30))

num__area_total_m2                          36.907163
num__estrato                                22.606820
num__antiguedad_de_la_vivienda              -3.880963
cat__municipio_Manizales                    -2.001855
cat__acceso_a_gas_Yes                       -1.473359
cat__municipio_Pereira                      -1.307615
cat__municipio_Cartagena                    -1.006688
cat__tipo_de_vivienda_Farm                   0.970065
cat__municipio_Bogotá                       -0.920099
cat__acceso_a_agua_potable_Yes               0.685844
cat__municipio_Bucaramanga                  -0.629143
cat__tipo_de_vivienda_House                  0.608555
num__habitaciones                            0.521287
num__ingreso_del_hogar                      -0.410856
num__parqueaderos                           -0.275791
num__banos                                  -0.211882
cat__acceso_a_transporte_publico_Yes         0.187487
cat__acceso_a_internet_Yes                  -0.162695
cat__zona_urbana_rural_Urban                -0.076189
cat__municipio_Medellín                      0.030736
num__distancia_al_centro_de_la_ciudad_km    -0.021527
cat__municipio_Cali                          0.007459
dtype: float64

In [22]:
# =========================================================== #
# 13. GRAFICAR IMPORTANCIA DE VARIABLES MEDIANTE COEFICIENTES #
# =========================================================== #

# NOMBRES VARIABLES
feature_names = model.named_steps[
    'preprocessing'
].get_feature_names_out()

# COEFICIENTES
coefficients = model.named_steps[
    'regressor'
].coef_

# DATAFRAME IMPORTANCIA
importance = pd.DataFrame({
    'Variable': feature_names,
    'Coeficiente': coefficients
})

importance['Importancia'] = (
    importance['Coeficiente']
    .abs()
)

# TOP VARIABLES
top_n = 15

importance_top = (
    importance
    .sort_values(
        by='Importancia',
        ascending=True
    )
    .tail(top_n)
)

# COLOR POSITIVO / NEGATIVO
importance_top['Signo'] = np.where(
    importance_top['Coeficiente'] >= 0,
    'Positivo',
    'Negativo'
)

# GRÁFICO INTERACTIVO
fig = px.bar(
    importance_top,
    x='Coeficiente',
    y='Variable',
    color='Signo',
    orientation='h',
    text='Coeficiente'
)

# LÍNEA CENTRAL
fig.add_vline(
    x=0,
    line_width=2,
    line_dash='dash'
)

# PERSONALIZACIÓN
fig.update_traces(
    texttemplate='%{text:.4f}',
    textposition='outside',
    marker_line_width=1,
    hovertemplate=
    '<b>Variable</b>: %{y}<br>' +
    '<b>Coeficiente</b>: %{x:.4f}<extra></extra>'
)

# LAYOUT
fig.update_layout(
    template='plotly_white',
    title={
        'text':'Importancia de Variables mediante Coeficientes',
        'x':0.5,
        'font':{'size':28}
    },
    xaxis_title='Valor del Coeficiente',
    yaxis_title='Variables',
    width=1300,
    height=800,
    legend_title='Signo del Coeficiente'
)

# EJES
fig.update_xaxes(
    showgrid=True
)

fig.update_yaxes(
    showgrid=False
)

# MOSTRAR
fig.show()

In [ ]:
# ================ #
# ¿QUÉ ES "model"? #
# ================ #

model

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **ENTRENAMIENTO DE MODELO FINAL (Full Data)**

Entrenar el modelo final con todos los datos es importante porque permite usar toda la información disponible para ajustar mejor los parámetros y obtener predicciones más precisas. Después de validar que el modelo funciona bien, ya no tiene sentido dejar datos sin usar. Este paso mejora la estabilidad del modelo y es el que se utiliza antes de llevarlo a producción, donde se espera el mejor desempeño posible.

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **SERIALIZACIÓN DE MODELOS**

### **¿Qué es .joblib?**

.joblib es una herramienta de Python diseñada para serializar objetos (guardarlos en disco) de forma eficiente, especialmente:

- Modelos de Machine Learning

- Pipelines de scikit-learn

- Objetos grandes con arrays de numpy

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **¿Qué significa “serializar”?**

Convertir un objeto en memoria a un archivo.

*Modelo en RAM  →  archivo .joblib  →  volver a cargarlo*

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">    </div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **¿Qué guarda exactamente?**

Cuando se ejecuta 

```
joblib.dump(model, "modelo.joblib")
```

Se guarda:

- Estructura del modelo

- Parámetros aprendidos (coeficientes)

- Transformaciones (OneHotEncoder, scaler)

- Estado completo del pipeline


<div align="center">
  <span style="font-size: 2em; font-weight: bold;">"Es una copia exacta del modelo entrenado”</span>
</div>


</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">    

### **Entrenamiento y Guardado del Modelo**

Este código construye un pipeline de Machine Learning que integra el preprocesamiento de los datos y un modelo de regresión lineal, permitiendo entrenarlo de forma consistente sobre todas las variables disponibles. Una vez ajustado el modelo con el conjunto completo de datos, se procede a guardar tanto el modelo entrenado como las variables utilizadas (features) en archivos .joblib dentro de una ruta específica del sistema. Esto facilita su reutilización en etapas posteriores como validación, despliegue o predicción en nuevos datos, garantizando reproducibilidad y organización del proyecto.

</div>

In [23]:
# ================ #
# CARGAR LIBRERÍAS #
# ================ #

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from pathlib import Path
import joblib

# ======== #
# PIPELINE #
# ======== #

model = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('regressor', LinearRegression())
])

# ============================= #
# ENTRENAMIENTO FINAL FULL DATA #
# ============================= #
model.fit(X, y)

# ==================================== #
# CARPETA DONDE SE GUARDARÁ EL .joblib #
# ==================================== #
ruta = Path("/Users/duvancatano/Documents/Estadistica_Analitica_Datos_UPTC_2026-2/models")

# ========================= #
# CREAR CARPETA SINO EXISTE #
# ========================= #
ruta.mkdir(parents=True, exist_ok=True)

# ============== #
# GUARDAR MODELO #
# ============== #
joblib.dump(model,ruta / "model_linear_regression.joblib")

# ================ #
# GUARDAR FEATURES #
# ================ #
joblib.dump(X.columns.tolist(), ruta / "features_linear_regression.joblib")

['/Users/duvancatano/Documents/Estadistica_Analitica_Datos_UPTC_2026-2/models/features_linear_regression.joblib']

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">    

### **SERIALIZACIÓN ALTERNATIVA**

### **¿Qué es .pkl?**

.pkl (pickle) es un formato de serialización estándar de Python que permite guardar objetos en disco.

---

### **¿Qué puedes guardar con .pkl?**

- Modelos de Machine Learning

- Pipelines

- DataFrames

- Listas, diccionarios, funciones

---

| Característica | `.pkl` (pickle) | `.joblib`     |
| -------------- | --------------- | ------------- |
| Tipo           | General         | Optimizado ML |
| Velocidad      | Media           | Más rápida    |
| Tamaño         | Mayor           | Más eficiente |
| Numpy arrays   | No optimizado   | Optimizado    |
| Uso típico     | General Python  | ML / sklearn  |

</div>

---

In [ ]:
# ========================= #
# GUARDAR CON PICKLE (.pkl) #
# ========================= #

import pickle

with open("modelo.pkl", "wb") as f:
    pickle.dump(model, f)

In [ ]:
# ======================= #
# CARGAR EL MODELO PICKLE #
# ======================= #

with open("modelo.pkl", "rb") as f:
    modelo_cargado = pickle.load(f)

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">    

<h1 align="center"><b>Regresión Lineal - Statmodels</b></h1> 

La regresión lineal con <strong>statsmodels</strong> en Python es una herramienta fundamental cuando el objetivo no es solo predecir, sino también <strong>interpretar y realizar inferencia estadística</strong> sobre las relaciones entre variables. A diferencia de enfoques orientados exclusivamente a Machine Learning, <strong>statsmodels</strong> permite obtener un análisis detallado del modelo, incluyendo coeficientes, errores estándar, pruebas de hipótesis, intervalos de confianza y medidas de ajuste. Esto la convierte en una opción ideal en contextos académicos, econométricos y de investigación, donde es clave comprender el impacto de cada variable y validar los supuestos del modelo.

</div>

---

In [ ]:
# ================ #
# Cargar Librarías #
# ================ #

import statsmodels.api as sm
import pandas as pd

In [ ]:
# ============================== #
# Codificación de la información #
# ============================== #

X_train_encoded = model.named_steps['preprocessing'].transform(X_train)
feature_names = model.named_steps['preprocessing'].get_feature_names_out()
X_train_encoded = pd.DataFrame(X_train_encoded, columns=feature_names)

In [ ]:
# ================= #
# Ajuste del modelo #
# ================= #

X_train_encoded = X_train_encoded.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)

# Agregar constante
X_sm = sm.add_constant(X_train_encoded)

# Ajustar modelo
model_sm = sm.OLS(y_train, X_sm).fit()

print(model_sm.summary())

In [ ]:
# =================================================================== # 
# Diagnóstico errores (residuos) de las predicciones de entrenamiento #
# =================================================================== # 

residuals = model_sm.resid
fitted = model_sm.fittedvalues

In [ ]:
# ================ #
# Gráfico residual #
# ================ #

df_resid = pd.DataFrame({
    "Ajustados": fitted,
    "Residuales": residuals
})

# SCATTER INTERACTIVO
fig = px.scatter(
    df_resid,
    x="Ajustados",
    y="Residuales",
    opacity=0.7,
    trendline="lowess",
    trendline_color_override="red"
)

# LÍNEA HORIZONTAL y=0
fig.add_hline(
    y=0,
    line_dash="dash",
    line_width=2,
    annotation_text="Residuo = 0"
)

# LAYOUT
fig.update_traces(
    marker=dict(size=8),
    hovertemplate=
    "<b>Valor Ajustado</b>: %{x:.2f}<br>"
    "<b>Residual</b>: %{y:.2f}<extra></extra>"
)

fig.update_layout(
    template="plotly_white",
    title={
        "text":"Análisis de Residuales vs Valores Ajustados",
        "x":0.5,
        "font":{"size":28}
    },
    xaxis_title="Valores Ajustados",
    yaxis_title="Residuales",
    width=1100,
    height=700
)

fig.update_xaxes(showgrid=True)
fig.update_yaxes(showgrid=True)

fig.show()

In [ ]:
# ================= #
# Densidad residual #
# ================= #

df_resid = pd.DataFrame({
    "Residual": residuals
})

# ESTADÍSTICAS
media = residuals.mean()
std = residuals.std()
asimetria = skew(residuals)
curt = kurtosis(residuals)

# HISTOGRAMA + KDE
fig = px.histogram(
    df_resid,
    x="Residual",
    nbins=30,
    marginal="box",
    histnorm="probability density"
)

# LÍNEA MEDIA
fig.add_vline(
    x=media,
    line_dash="dash",
    line_width=3,
    annotation_text=f"Media = {media:.2f}"
)

# LAYOUT
fig.update_traces(
    hovertemplate=
    "<b>Residual</b>: %{x:.2f}<br>" +
    "<b>Densidad</b>: %{y:.4f}<extra></extra>"
)

fig.update_layout(
    template="plotly_white",
    title={
        "text":
        "Distribución de los Residuales"
        f"<br><sup>Media={media:.2f} | Desv.Std={std:.2f} | "
        f"Asimetría={asimetria:.2f} | Curtosis={curt:.2f}</sup>",
        "x":0.5,
        "font":{"size":28}
    },
    xaxis_title="Residuales",
    yaxis_title="Densidad",
    width=1100,
    height=700,
    bargap=0.05
)

fig.show()

In [ ]:
# ==================== #
# Prueba de normalidad #
# ==================== #

from statsmodels.stats.stattools import jarque_bera

alpha = 0.05

jb_stat, p_value, skewness, kurtosis = jarque_bera(residuals)

print("="*21)
print("PRUEBA DE JARQUE-BERA")
print("="*21)

print("\nHipótesis:")
print("H0: Los residuales siguen una distribución normal.")
print("H1: Los residuales NO siguen una distribución normal.")

print("\nResultados:")
print(f"JB Statistic = {jb_stat:.4f}")
print(f"p-value      = {p_value:.4f}")

print("\nRegla de decisión:")
print(f"Si p-value < {alpha}, se rechaza H0.")
print(f"Si p-value ≥ {alpha}, no se rechaza H0.")

print("\nConclusión:")

if p_value < alpha:
    print(f"Como {p_value:.4f} < {alpha}, se rechaza H0.")
    print("Existe evidencia de que los residuales NO son normales.")
else:
    print(f"Como {p_value:.4f} ≥ {alpha}, no se rechaza H0.")
    print("No existe evidencia suficiente para afirmar que los residuales no son normales.")

print("="*80)

In [ ]:
# =========== #  
# Diagnóstico #  
# =========== #  

from statsmodels.stats.diagnostic import het_breuschpagan

alpha = 0.05

lm_stat, p_value, f_stat, f_pvalue = het_breuschpagan(
    residuals,
    model_sm.model.exog
)

# HIPÓTESIS
print("="*23)
print("PRUEBA DE BREUSCH-PAGAN")
print("="*23)

print("\nHipótesis:")
print("H0: Los errores tienen varianza constante (Homocedasticidad)")
print("H1: Los errores NO tienen varianza constante (Heterocedasticidad)")

# RESULTADOS
print("\nResultados:")
print(f"LM Statistic = {lm_stat:.4f}")
print(f"p-value      = {p_value:.4f}")

# REGLA DE DECISIÓN
print("\nRegla de decisión:")
print(f"Nivel de significancia α = {alpha}")

if p_value < alpha:
    print(f"Como p-value = {p_value:.4f} < {alpha}, se rechaza H0.")
    print("Conclusión: Existe evidencia de heterocedasticidad.")
else:
    print(f"Como p-value = {p_value:.4f} ≥ {alpha}, no se rechaza H0.")
    print("Conclusión: No existe evidencia de heterocedasticidad.")

print("="*60)

---

## **Ejecución en Terminal**

```> streamlit run src/housing_pred_stream.py```

---

# 🎬 **¡FIN!**

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">    </div>