---

<div align="center">

# **REGRESIÓN LOGÍSTICA CON PYTHON - SKLEARN**

<div align="center">
  <img src="img/logo_uptc2.jpg" width="120">
</div>

**Profesor:** Duván Cataño  

**Curso:** Estadística para Analítica de Datos 

**Universidad Pedagógica y Tecnológica de Colombia**
</div>

---


<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 


## **Introducción**

La Regresión Logística es un método estadístico utilizado para modelar la probabilidad de una variable binaria en función de una o más variables independientes, siendo ampliamente empleada en problemas de clasificación binaria. Cuando utiliza una sola variable predictora se denomina regresión logística simple, y cuando incorpora varias, regresión logística múltiple. En Python, las implementaciones más utilizadas son ```scikit-learn```, enfocada en predicción y Machine Learning, y ```statsmodels```, orientada además al análisis estadístico e inferencia del modelo.

En este notebook nos enfocamos a la implementación en ```scikit-learn```. Para investigar la metodología desarrollada en ```statsmodels``` consultar el *Capítulo 7* del siguiente texto : 📕 <a href="https://faculty.ksu.edu.sa/sites/default/files/an-introduction-to-generalized-linear-models_compress.pdf#page=167.80"> MLG</a>

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Idea Fundamental**

- La Regresión Lineal no es adecuada para clasificación porque puede producir valores fuera del rango : $(-\infty,\infty)$

- Sin embargo, una probabilidad debe estar entre : $[0,1]$

- Por ello, la regresión logística utiliza una transformación logística (sigmoide) que convierte cualquier valor real en una probabilidad.

</div>

---

<p align="center">
<img src="img/lin_log.jpg" width="1200" height="500">
</p>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Función Sigmoide**

La función logística o sigmoide es:

$$p(z)=\frac{1}{1+e^{-z}}$$

donde:

$$
z=\beta_0+\beta_1x_1+\beta_2x_2+\cdots+\beta_px_p
$$

</div>

<p align="center">
<img src="img/sigmoi.png" width="1200" height="500">
</p>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Interpretación**

- Si $z$ $\rightarrow$ $\infty$, entonces $p(z)\rightarrow 1$

- Si $z$ $\rightarrow$ $-\infty$, entonces $p(z)\rightarrow 0$

- Si $z=0$, entonces $p(z)=0.5$

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Definición**

La Regresión Logística es un modelo probabilístico de clasificación binaria que estima la probabilidad de que una observación pertenezca a una clase positiva, codificada con ```(Y=1)```.
Sea $X = (x_1, x_2, \dots, x_p)$ un vector de variables predictoras. La Regresión Logística modela la probabilidad:

$$\mathbb{P}(Y=1|X),$$

mediante la función logística o sigmoide dada por:

$$\mathbb{P}(Y=1|X)=\frac{1}{1+e^{-z}},$$

donde $z = \beta_0 + \beta_1x_1 + \beta_2x_2 + \cdots + \beta_px_p.$

Equivalentemente:

$$\mathbb{P}(Y=1|X)=\frac{e^{\beta_0+\beta_1x_1+\cdots+\beta_px_p}}{1+e^{\beta_0+\beta_1x_1+\cdots+\beta_px_p}}$$


En ```Scikit-Learn```, los parámetros:

$$\beta_0,\beta_1,\dots,\beta_p,$$

se estiman mediante optimización numérica basada en *Máxima Verosimilitud* y *Regularización*. Modelar el ```log of odds``` es la estrategia matemática que permite encontrar los valores de los coeficientes.

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Interpretación de los Coeficientes**

- Los $\beta_j$, para $j = 0, \ldots, p$, 

representan el efecto de la variable $x_j$, sobre el logaritmo de las probabilidades relativas.

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Odds (Razón de Probabilidades)**

Las odds se definen como:

$$
\text{Odds}=
\frac{p(x)}{1-p(x)}
$$


### **Interpretación**

- Odds > 1 → más probable que ocurra el evento

- Odds < 1 → menos probable

- Odds = 1 → igual probabilidad

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Logit**

Aplicando logaritmo:

$$
\log
\left(
\frac{p(x)}{1-p(x)}
\right)
=
\beta_0+\beta_1x_1+\cdots+\beta_px_p
$$

Esta expresión se conoce como:

- ```Logit```

- ```Log-Odds```

La regresión logística es lineal en el espacio de ```Log-Odds```.

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Regla de Clasificación**

Una vez estimada la probabilidad:

$$
\hat p(x)
$$

el modelo clasifica usando un umbral:

$$
\hat y=
\begin{cases}
1 & \text{si } \hat p(x)\ge 0.5 \\
0 & \text{si } \hat p(x)<0.5
\end{cases}
$$

No obstante, en la práctica, dicho umbral puede ser variable dependiendo de los intereses del negocio.

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Función de Pérdida**

```Scikit-Learn``` estima los parámetros usando Máxima Verosimilitud. En este casi la log-verosimilitud es definida:

$$
\ell(\beta)=
\sum_{i=1}^{n}
\left[
y_i\log(p_i)
+
(1-y_i)\log(1-p_i)
\right],
$$

donde:

$$
p_i=P(Y_i=1|X_i).
$$

El Objetivo es **Maximizar** : $\ell(\beta)$


</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Regularización en Scikit-Learn**

Scikit-Learn incorpora regularización para evitar sobreajuste.

La función optimizada es:

$$
\min_{\beta}
\left[
-\ell(\beta)
+
\lambda R(\beta)
\right]
$$

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

**Regularización $L^2$ (Ridge)**

La penalización $L^2$ es:

$$
R(\beta)=
\sum_{j=1}^{p}\beta_j^2
$$

### **Interpretación**

- Reduce coeficientes muy grandes

- Mejora generalización

- Reduce varianza

- No elimina variables


</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

**Regularización L1 (LASSO)**

La penalización L1 es:

$$
R(\beta)=
\sum_{j=1}^{p}|\beta_j|
$$

### **Interpretación**

- Puede hacer coeficientes exactamente cero
 
- Realiza selección automática de variables
 
- Produce modelos más sparsos

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Parámetro C en Scikit-Learn**

En `sklearn`, el parámetro:

$$
C=\frac{1}{\lambda}
$$


se interpreta como:

- $C$ grande → poca regularización

- $C$ pequeño → mucha regularización

- La regularización penaliza coeficientes demasiado grandes para evitar sobreajuste.

---

### Ejemplo :

- $C=100$ : El modelo aprende patrones complejos.

- $C=0.01$ : El modelo es más conservador.

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Función Objetivo en Scikit-Learn**

Con regularización L2:

$$
\min_{\beta}
\left[
-\ell(\beta)
+
\frac{1}{2C}
\sum_{j=1}^{p}\beta_j^2
\right]
$$

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Solvers en Scikit-Learn**

En Regresión Logística, los parámetros del modelo no tienen una solución cerrada simple como en regresión lineal. Por ello, ```Scikit-Learn``` utiliza algoritmos numéricos iterativos llamados Solvers para optimizar la función objetivo.

### - *liblinear*

- Excelente para clasificación binaria
- Soporta L1 y L2
- Muy estable

### - *lbfgs*

- Muy usado por defecto
- Excelente para datasets medianos/grandes
- Solo L2

### - *saga*

- Soporta:
  - L1
  - L2
  - ElasticNet

- Escalable a datasets grandes

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Class Weight**

Para clases desbalanceadas: ```class_weight='balanced'```

Scikit-Learn ajusta pesos automáticamente:

$$
w_j=
\frac{n}{k\cdot n_j},
$$

donde:

- $n$ = total observaciones

- $k$ = número de clases

- $n_j$ = observaciones de la clase $j$

En este caso la clase **minoritaria** recibe mayor importancia.

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

### **Interpretación de Variables**

- Si $\beta_j>0$, entonces la variable aumenta la probabilidad de clase 1.

- Si $\beta_j<0$, la variable reduce la probabilidad de clase 1.

- Mientras mayor sea: $|\beta_j|$, mayor influencia tiene la variable.

    - coeficientes grandes → variables relevantes
    - coeficientes cercanos a cero → poca influencia

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">

<div align="center">

| Ventajas | Desventajas |
|---|---|
| ✅ Fácil interpretación | ❌ Supone relación lineal en log-odds |
| ✅ Modelo probabilístico | ❌ Limitada para relaciones altamente no lineales |
| ✅ Muy rápida computacionalmente | ❌ Sensible a multicolinealidad |
| ✅ Funciona bien en clasificación binaria | ❌ Puede subajustar problemas complejos |
| ✅ Robusta con regularización |  |
| ✅ Buena interpretabilidad de variables |  |

</div>

</div>

---

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">

<h1 align="center"><b>Modelación con Regresión Logística - Spam</b></h1> 

</div>

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;"> 

## **Descripción General de los Datos**

La base de datos corresponde a un conjunto de correos electrónicos utilizado para el análisis y detección automática de spam mediante técnicas de Modelación. Cada observación representa un correo electrónico y las variables describen características textuales y tipográficas extraídas de su contenido. Las variables incluyen principalmente:

- Frecuencias de palabras específicas asociadas a correos spam,
- Frecuencias de caracteres especiales,
- Patrones de uso de mayúsculas,
- Términos relacionados con promociones, negocios o tecnología.

Muchas variables representan el porcentaje de aparición de ciertas palabras dentro del correo electrónico, por ejemplo:

- `free`
- `money`
- `credit`
- `business`
- `remove`

las cuales suelen ser frecuentes en mensajes spam.

Además, el conjunto de datos contiene variables relacionadas con:

- Signos de puntuación (`!`, `$`, `#`),
- Cadenas numéricas frecuentes,
- Estadísticas sobre letras mayúsculas.

La variable objetivo es:

<div align="center">

| Variable | Descripción |
|---|---|
| `type` | 1 = Spam, 0= No Spam |

</div>

El objetivo principal es construir Modelos de Clasificación capaces de identificar automáticamente correos spam a partir de patrones lingüísticos y estadísticos presentes en los mensajes.

</div>

<p align="center">
<img src="img/spam_img.png" width="700" height="400">
</p>

---


<div align="center">

## **Diccionario de Variables**

| **VARIABLE** | **DESCRIPCIÓN** |
|---|---|
| make | Frecuencia de la palabra "make" |
| address | Frecuencia de la palabra "address" |
| all | Frecuencia de la palabra "all" |
| num3d | Frecuencia de la cadena "3d" |
| our | Frecuencia de la palabra "our" |
| over | Frecuencia de la palabra "over" |
| remove | Frecuencia de la palabra "remove" |
| internet | Frecuencia de la palabra "internet" |
| order | Frecuencia de la palabra "order" |
| mail | Frecuencia de la palabra "mail" |
| receive | Frecuencia de la palabra "receive" |
| will | Frecuencia de la palabra "will" |
| people | Frecuencia de la palabra "people" |
| report | Frecuencia de la palabra "report" |
| addresses | Frecuencia de la palabra "addresses" |
| free | Frecuencia de la palabra "free" |
| business | Frecuencia de la palabra "business" |
| email | Frecuencia de la palabra "email" |
| you | Frecuencia de la palabra "you" |
| credit | Frecuencia de la palabra "credit" |
| your | Frecuencia de la palabra "your" |
| font | Frecuencia de la palabra "font" |
| num000 | Frecuencia de la cadena "000" |
| money | Frecuencia de la palabra "money" |
| hp | Frecuencia de la palabra "hp" |
| hpl | Frecuencia de la palabra "hpl" |
| george | Frecuencia de la palabra "george" |
| num650 | Frecuencia de la cadena "650" |
| lab | Frecuencia de la palabra "lab" |
| labs | Frecuencia de la palabra "labs" |
| telnet | Frecuencia de la palabra "telnet" |
| num857 | Frecuencia de la cadena "857" |
| data | Frecuencia de la palabra "data" |
| num415 | Frecuencia de la cadena "415" |
| num85 | Frecuencia de la cadena "85" |
| technology | Frecuencia de la palabra "technology" |
| num1999 | Frecuencia de la cadena "1999" |
| parts | Frecuencia de la palabra "parts" |
| pm | Frecuencia de la palabra "pm" |
| direct | Frecuencia de la palabra "direct" |
| cs | Frecuencia de la palabra "cs" |
| meeting | Frecuencia de la palabra "meeting" |
| original | Frecuencia de la palabra "original" |
| project | Frecuencia de la palabra "project" |
| re | Frecuencia de la palabra "re" |
| edu | Frecuencia de la palabra "edu" |
| table | Frecuencia de la palabra "table" |
| conference | Frecuencia de la palabra "conference" |
| charSemicolon | Frecuencia del carácter ";" |
| charRoundbracket | Frecuencia del carácter "(" |
| charSquarebracket | Frecuencia del carácter "[" |
| charExclamation | Frecuencia del carácter "!" |
| charDollar | Frecuencia del carácter "$" |
| charHash | Frecuencia del carácter "#" |
| capitalAve | Promedio de longitud de secuencias en mayúsculas |
| capitalLong | Longitud máxima de secuencias en mayúsculas |
| capitalTotal | Número total de letras mayúsculas |
| type | Variable objetivo: 1 = Spam, 0 = No Spam |

---
---

</div>

In [1]:
# ============ #
# 1. LIBRERÍAS #
# ============ #

import pandas as pd
import numpy as np
import os
import joblib
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pathlib import Path
from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve
)

In [2]:
# =================== #
# 2. LECTURA DE RUTAS #
# =================== #

mainpath= "/Users/duvancatano/Documents/Estadistica_Analitica_Datos_UPTC_2026-2/data/spam"
filename= "spam_dataset.csv"
fullpath= os.path.join(mainpath,filename)

In [3]:
# ================= #
# 3. CARGA DE DATOS #
# ================= #

data = pd.read_csv(fullpath, sep=",") # El separador es "," porque en el archivo .csv los valores están separados por coma
pd.set_option('display.max_columns', None) # Para mostrar todas las columnas del DataFrame sin truncar
data.sample(10)

,make,address,all,num3d,our,over,remove,internet,order,mail,receive,will,people,report,addresses,free,business,email,you,credit,your,font,num000,money,hp,hpl,george,num650,lab,labs,telnet,num857,data,num415,num85,technology,num1999,parts,pm,direct,cs,meeting,original,project,re,edu,table,conference,charSemicolon,charRoundbracket,charSquarebracket,charExclamation,charDollar,charHash,capitalAve,capitalLong,capitalTotal,type
4545,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.80,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.80,0.0,0.0,0.0,0.00,0.0,0.00,0.8,0.80,0.80,0.00,0.00,0.000,0.149,0.000,0.000,0.000,0.000,1.900,15,57,nonspam
3032,0.00,0.00,2.17,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,2.17,8.69,0.0,6.52,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.00,2.17,0.00,0.000,0.000,0.000,0.000,0.000,0.000,1.333,3,8,nonspam
203,0.43,0.00,0.43,0.0,0.43,0.00,0.86,0.00,0.00,0.00,0.00,0.43,0.0,0.0,0.0,0.00,0.86,0.43,1.29,0.0,4.76,0.0,0.00,1.29,0.00,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.140,0.000,0.000,0.915,0.000,0.000,3.891,47,144,spam
1304,0.10,0.10,0.70,0.0,0.60,0.20,0.40,0.10,1.41,0.81,0.10,0.50,0.0,0.0,0.0,0.10,0.00,1.11,2.22,0.4,1.92,0.0,0.00,0.30,0.00,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.1,0.0,0.00,0.0,0.1,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.000,0.000,0.260,0.994,0.391,0.032,3.176,56,1042,spam
2189,0.00,0.44,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.29,0.00,0.29,0.0,0.0,0.0,0.00,0.14,0.00,0.00,0.0,0.29,0.0,0.00,0.00,0.44,0.0,0.00,0.0,0.0,0.89,0.0,0.0,0.0,0.0,0.0,0.0,0.89,0.0,0.0,0.0,0.59,0.0,0.14,0.0,0.00,0.89,0.00,0.44,0.101,0.135,0.016,0.000,0.000,0.000,2.297,46,680,nonspam
1498,0.47,0.00,0.95,0.0,0.95,0.00,0.95,0.00,0.00,0.00,0.00,0.47,0.0,0.0,0.0,0.47,0.47,0.00,4.28,0.0,0.95,0.0,1.42,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.47,0.00,0.00,0.00,0.000,0.076,0.000,1.306,0.230,0.000,6.027,91,217,spam
4164,0.00,0.00,0.50,0.0,0.00,0.50,0.00,0.00,0.00,0.00,0.00,0.00,1.0,0.0,0.0,0.00,0.00,0.00,2.00,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,1.00,0.50,0.00,0.00,0.000,0.000,0.000,0.000,0.000,0.000,2.527,47,91,nonspam
2217,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.0,6.66,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,1.204,0.000,0.000,0.000,0.000,0.000,1.285,2,9,nonspam
3312,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,5.26,0.00,0.00,0.00,0.0,0.0,0.0,0.00,2.63,0.00,2.63,0.0,5.26,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.000,0.000,0.000,0.000,0.000,0.000,2.058,11,35,nonspam
4387,0.00,0.36,0.36,0.0,0.00,0.36,0.00,0.73,0.00,0.36,0.36,1.46,0.0,0.0,0.0,0.36,0.00,2.56,2.93,0.0,0.36,0.0,0.00,0.73,0.00,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.36,0.0,0.00,0.00,0.00,0.00,0.000,0.000,0.000,0.000,0.123,0.000,2.854,68,157,nonspam

---
## **Funciones Peronalizadas - Valores Perdidos y Nulos**
---

In [4]:
# Porcentaje de valores perdidos por variable
def resum_missing(df):
    total = df.isnull().sum().sort_values(ascending=False)
    percent = (df.isnull().sum() *100/df.isnull().count()).sort_values(ascending=False)
    missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Porcentaje'])
    return missing_data

# Resumen de posición de valores perdidos
def posmissing(df):
    lista_miss = np.where(df.isna())
    v1 = pd.Series(np.ndarray.tolist(lista_miss[0]))
    v2 = pd.Series(np.ndarray.tolist(lista_miss[1]))
    resumen_vna = pd.concat([v1, v2], axis=1, keys=['posicion_fila', 'posicion_columna'])
    return resumen_vna

# Construcción función que cuenta ceros
def count_zeros(df):
    total = (df == 0).astype(int).sum(axis=0)
    percent = ((df == 0).astype(int).sum(axis=0) *100/df.count())
    missing_data = pd.concat([total, percent], axis=1, keys=['Total_ceros', 'Porcentaje'])
    return missing_data.sort_values(by='Porcentaje', ascending=False)

# Verificar si hay valores perdidos
resum_missing(data)

                   Total  Porcentaje
make                   0         0.0
project                0         0.0
num857                 0         0.0
data                   0         0.0
num415                 0         0.0
num85                  0         0.0
technology             0         0.0
num1999                0         0.0
parts                  0         0.0
pm                     0         0.0
direct                 0         0.0
cs                     0         0.0
meeting                0         0.0
original               0         0.0
re                     0         0.0
address                0         0.0
edu                    0         0.0
table                  0         0.0
conference             0         0.0
charSemicolon          0         0.0
charRoundbracket       0         0.0
charSquarebracket      0         0.0
charExclamation        0         0.0
charDollar             0         0.0
charHash               0         0.0
capitalAve             0         0.0
capitalLong            0         0.0
capitalTotal           0         0.0
telnet                 0         0.0
labs                   0         0.0
lab                    0         0.0
num650                 0         0.0
all                    0         0.0
num3d                  0         0.0
our                    0         0.0
over                   0         0.0
remove                 0         0.0
internet               0         0.0
order                  0         0.0
mail                   0         0.0
receive                0         0.0
will                   0         0.0
people                 0         0.0
report                 0         0.0
addresses              0         0.0
free                   0         0.0
business               0         0.0
email                  0         0.0
you                    0         0.0
credit                 0         0.0
your                   0         0.0
font                   0         0.0
num000                 0         0.0
money                  0         0.0
hp                     0         0.0
hpl                    0         0.0
george                 0         0.0
type                   0         0.0

In [5]:
# ==================== #
# 4. VARIABLE OBJETIVO #
# ==================== #

# 1 = Spam
# 0 = No Spam

data["type"] = np.where(
    data["type"] == "spam",
    1,
    0
)

In [6]:
# ================================= #
# 5. VARIABLES PREDICTORAS Y TARGET #
# ================================= #

X = data.drop(columns=["type"])
y = data["type"]

In [8]:
# ==================================== #
# 6. VARIABLES NUMÉRICAS Y CATEGÓRICAS #
# ==================================== #

cat_cols = X.select_dtypes(
    include=["object", "category"]
).columns.tolist() # Aunque no tenemos categóricas, se deja si en el futuro se incluye alguna

num_cols = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist() # Se combina variables de tipo entero y real

In [9]:
# =================== #
# 7. PREPROCESAMIENTO #
# =================== #

preprocessor = ColumnTransformer([

    (
        "cat",
        OneHotEncoder(
            drop="first",
            handle_unknown="ignore"
        ),
        cat_cols
    ),

    (
        "num",
        StandardScaler(),
        num_cols
    )

])

In [10]:
# ================= #
# 8. TRANSFORMACIÓN #
# ================= #

X_processed = preprocessor.fit_transform(X)
print("Dimensión final:", X_processed.shape)

# Visualización de covariuables preprocesadas
print("Visualizaciónc:", X_processed[1,])

Dimensión final: (4601, 57)
Visualizaciónc: [ 0.3453594   0.05190919  0.43512954 -0.04689958 -0.25611729  0.67239929
  0.24474325 -0.0880101  -0.32330236  1.0867113   0.74520639  0.28818107
  1.84739108  0.4516628   0.35081184 -0.1318249  -0.16348027  0.17936681
  1.0183704  -0.16789311  0.64983137 -0.11817151  0.93749108  0.75856508
 -0.32881467 -0.29923993 -0.22789481 -0.23183016 -0.16673145 -0.22523952
 -0.16053931 -0.14321202 -0.17492026 -0.14521515 -0.19806739 -0.24213022
 -0.15812941 -0.05983624 -0.18091134 -0.18530385 -0.12090468 -0.17259996
 -0.20599311 -0.12734332 -0.29777621 -0.19738748 -0.0713879  -0.11154623
 -0.15845336 -0.02600722 -0.15519768  0.12620315  0.42378306  0.00876271
 -0.00244327  0.25056283  1.22832407]

In [11]:
# ========================= #
# 9. PARTICIÓN TRAIN - TEST #
# ========================= #

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,  
    random_state=123,
    stratify=y
)

# PREPROCESAMIENTO 
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

# DIMENSIONES
print("X_train:", X_train_processed.shape)
print("X_test :", X_test_processed.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (3220, 57)
X_test : (1381, 57)
y_train: (3220,)
y_test : (1381,)

In [12]:
# ================================ #
# 10. PIPELINE REGRESIÓN LOGÍSTICA #
# ================================ #

pipeline_logit = Pipeline([
    (
        "preprocessing",
        preprocessor
    ),
    (
        "model",
        LogisticRegression(
            max_iter=1000,
            random_state=123
        )
    )
])

In [13]:
# ================= #
# 10. ENTRENAMIENTO #
# ================= #

pipeline_logit.fit(
    X_train,
    y_train
)
print("Modelo entrenado correctamente")

Modelo entrenado correctamente

In [15]:
# ================ #
# 11. PREDICCIONES #
# ================ #

y_pred = pipeline_logit.predict(X_test)
y_prob = pipeline_logit.predict_proba(X_test)[:,1]

In [16]:
# ============================= #
# 12. MÉTRICAS DE CLASIFICACIÓN #
# ============================= #

# MÉTRICAS
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)

# RESULTADOS
print("="*19)
print("MÉTRICAS DEL MODELO")
print("="*19)

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-Score : {f1:.4f}")
print(f"ROC-AUC  : {auc:.4f}")

# MATRIZ DE CONFUSIÓN
cm = confusion_matrix(y_test, y_pred)

cm_df = pd.DataFrame(
    cm,
    index=["No Spam", "Spam"],
    columns=["Pred No Spam", "Pred Spam"]
)

fig = px.imshow(
    cm_df,
    text_auto=True,
    color_continuous_scale="Blues",
    title="Matriz de Confusión"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5,
    height=500
)

fig.show()

# CLASSIFICATION REPORT
print("\n")
print("="*24)
print("REPORTE DE CLASIFICACIÓN")
print("="*24)

print(
    classification_report(
        y_test,
        y_pred,
        target_names=["No Spam", "Spam"]
    )
)

# CÁLCULO DE CURVA ROC 
fpr, tpr, thresholds = roc_curve(
    y_test,
    y_prob
)

fig = go.Figure()

# GRÁFICO DE CURVA ROC 
fig.add_trace(

    go.Scatter(
        x=fpr,
        y=tpr,
        mode="lines",
        name=f"ROC Curve (AUC = {auc:.4f})",
        line=dict(width=4)
    )
)

# LÍNEA ALEATORIA
fig.add_trace(

    go.Scatter(
        x=[0,1],
        y=[0,1],
        mode="lines",
        name="Random Classifier",
        line=dict(
            dash="dash"
        )
    )

)

fig.update_layout(

    template="plotly_dark",

    title={
        "text": "Curva ROC",
        "x": 0.5,
        "xanchor": "center"
    },

    xaxis_title="False Positive Rate",

    yaxis_title="True Positive Rate",

    height=600,

    width=700

)

fig.show()

===================
MÉTRICAS DEL MODELO
===================
Accuracy : 0.9211
Precision: 0.9223
Recall   : 0.8732
F1-Score : 0.8971
ROC-AUC  : 0.9711

========================
REPORTE DE CLASIFICACIÓN
========================
              precision    recall  f1-score   support

     No Spam       0.92      0.95      0.94       837
        Spam       0.92      0.87      0.90       544

    accuracy                           0.92      1381
   macro avg       0.92      0.91      0.92      1381
weighted avg       0.92      0.92      0.92      1381

---

## **Accuracy Global = 0.92**

El modelo clasifica correctamente el 92% de todos los correos, lo cual significa que de cada 100 correos aproximadamente 92 son clasificados correctamente.

---

## **Macro Average**

| Métrica | Valor |
|---|---|
| Precision | 0.92 |
| Recall | 0.91 |
| F1-score | 0.92 |

El promedio macro trata ambas clases con el mismo peso. El modelo tiene comportamiento equilibrado entre: *spam* y *no spam*

---

## **Weighted Average**

| Métrica | Valor |
|---|---|
| Precision | 0.92 |
| Recall | 0.92 |
| F1-score | 0.92 |

Este promedio considera el tamaño de cada clase, como hay más “No Spam” que “Spam”, esta métrica pondera por frecuencia.

---

<h1 align="center"><b>Reporte de Clasificación</b></h1> 

### **Clase : No Spam**

- *Precision = 0.92* : De todos los correos que el modelo predijo como No Spam, el $92\%$ realmente eran legítimos.


- *Recall = 0.95* : El modelo logra identificar correctamente el $95\%$ de todos los correos legítimos.


- *F1-score = 0.94* : El F1 combina precisión y recall en una sola medida, identifica correos legítimos, y no comete demasiados errores.


- *Support = 837* : Cantidad de correos legítimos en el conjunto de prueba.

---

### **Clase : Spam**

- *Precision = 0.92* : De todos los correos que el modelo marcó como spam, el $92\%$ realmente eran spam.


- *Recall = 0.87* : El modelo detecta correctamente el $87\%$ de los correos spam reales.


- *F1-score = 0.90* : Muy buen equilibrio entre detectar spam y evitar clasificaciones erróneas.

- *Support = 837* : Cantidad de correos legítimos en el conjunto de prueba.

---
## **Validación Cruzada**
---

In [17]:
# ======================== #
# 13. K-FOLD ESTRATIFICADO #
# ======================== #

cv = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=123
)

In [18]:
# ====================== #
# 14. MÉTRICAS A EVALUAR #
# ====================== #

metrics = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}

In [19]:
# ==================== #
# 15. CROSS VALIDATION #
# ==================== #

cv_results = cross_validate(
    estimator=pipeline_logit,
    X=X,
    y=y,
    cv=cv,
    scoring=metrics,
    return_train_score=False,
    n_jobs=-1
)

In [21]:
# ======================= #
# 16. RESULTADOS PROMEDIO #
# ======================= #

results_df = pd.DataFrame({
    "Métrica": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score",
        "ROC-AUC"
    ],

    "Promedio": [
        cv_results["test_accuracy"].mean(),
        cv_results["test_precision"].mean(),
        cv_results["test_recall"].mean(),
        cv_results["test_f1"].mean(),
        cv_results["test_roc_auc"].mean()
    ],

    "Desv. Std": [
        cv_results["test_accuracy"].std(),
        cv_results["test_precision"].std(),
        cv_results["test_recall"].std(),
        cv_results["test_f1"].std(),
        cv_results["test_roc_auc"].std()
    ]
})

results_df[["Promedio", "Desv. Std"]] = (
    results_df[["Promedio", "Desv. Std"]]
    .round(4)
)

In [22]:
# ====================== #
# 17. MOSTRAR RESULTADOS #
# ====================== #

print("\n")
print("="*29)
print("RESULTADOS VALIDACIÓN CRUZADA")
print("="*29)
print(results_df)

=============================
RESULTADOS VALIDACIÓN CRUZADA
=============================
     Métrica  Promedio  Desv. Std
0   Accuracy    0.9246     0.0143
1  Precision    0.9233     0.0196
2     Recall    0.8820     0.0229
3   F1-Score    0.9021     0.0190
4    ROC-AUC    0.9712     0.0087

In [23]:
# ======================= #
# 18. GRÁFICA DE MÉTRICAS #
# ======================= #

fig = px.bar(
    results_df,
    x="Métrica",
    y="Promedio",
    error_y="Desv. Std",
    color="Métrica",
    text="Promedio",
    title="Desempeño Promedio - Validación Cruzada"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5,
    height=550,
    showlegend=False,
    yaxis_title="Score"
)

fig.update_traces(
    texttemplate="%{text:.4f}",
    textposition="outside"
)

fig.show()

---
## **Ajuste de Hiperparámetros**
---

In [24]:
# ======================================= #
#   19. OPTIMIZACIÓN DE HIPERPARÁMETROS   #
# RANDOMIZED SEARCH - REGRESIÓN LOGÍSTICA #
# ======================================= #

from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import StratifiedKFold
from scipy.stats import uniform

In [25]:
# ====================== #
# 20. VALIDACIÓN CRUZADA #
# ====================== #

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=123
)

In [26]:
# ============================== #
# 21. ESPACIO DE HIPERPARÁMETROS #
# ============================== #

param_dist = {

    # Regularización
    "model__C": uniform(0.001, 20),

    # Tipo de penalización
    "model__penalty": ["l1", "l2"],

    # Solver compatible
    "model__solver": ["liblinear", "saga"],

    # Balanceo automático
    "model__class_weight": [
        None,
        "balanced"
    ]
}

In [27]:
# ================= #
# 22. RANDOM SEARCH #
# ================= #

random_search = RandomizedSearchCV(
    estimator=pipeline_logit,
    param_distributions=param_dist,
    n_iter=30,
    scoring="roc_auc",
    cv=cv,
    verbose=1,
    random_state=123,
    n_jobs=-1
)

In [28]:
# ================= #
# 23. ENTRENAMIENTO #
# ================= #

random_search.fit(
    X_train,
    y_train
)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=123, shuffle=True),
                   estimator=Pipeline(steps=[('preprocessing',
                                              ColumnTransformer(transformers=[('cat',
                                                                               OneHotEncoder(drop='first',
                                                                                             handle_unknown='ignore'),
                                                                               []),
                                                                              ('num',
                                                                               StandardScaler(),
                                                                               ['make',
                                                                                'address',
                                                                                'all',
                                                                                'num3d',
                                                                                'our',
                                                                                'over',
                                                                                'remove',
                                                                                'internet',
                                                                                'order',
                                                                                'mail',
                                                                                'receive',
                                                                                'will',
                                                                                'people',
                                                                                'r...
                                                                                'labs', ...])])),
                                             ('model',
                                              LogisticRegression(max_iter=1000,
                                                                 random_state=123))]),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'model__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x122b55be0>,
                                        'model__class_weight': [None,
                                                                'balanced'],
                                        'model__penalty': ['l1', 'l2'],
                                        'model__solver': ['liblinear', 'saga']},
                   random_state=123, scoring='roc_auc', verbose=1)

In [29]:
# ==================================== #
# 24. HIPERPARÁMETROS DEL MEJOR MODELO #
# ==================================== #

best_model = random_search.best_estimator_

print("\n")
print("="*23)
print("MEJORES HIPERPARÁMETROS")
print("="*23)

print(random_search.best_params_)

print("\n")
print("="*13)
print("MEJOR ROC-AUC")
print("="*13)

print(round(random_search.best_score_, 4))

=======================
MEJORES HIPERPARÁMETROS
=======================
{'model__C': np.float64(11.594885940452201), 'model__class_weight': 'balanced', 'model__penalty': 'l2', 'model__solver': 'liblinear'}


=============
MEJOR ROC-AUC
=============
0.9698

In [30]:
# ================ #
# 25. PREDICCIONES #
# ================ #

y_pred_best = best_model.predict(X_test)
y_prob_best = best_model.predict_proba(X_test)[:,1]

In [31]:
# ==================== #
# 26. MÉTRICAS FINALES #
# ==================== #

accuracy = accuracy_score(y_test, y_pred_best)
precision = precision_score(y_test, y_pred_best)
recall = recall_score(y_test, y_pred_best)
f1 = f1_score(y_test, y_pred_best)
auc = roc_auc_score(y_test, y_prob_best)

In [32]:
# ========== #
# RESULTADOS #
# ========== #

results_final = pd.DataFrame({

    "Métrica": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score",
        "ROC-AUC"
    ],

    "Valor": [
        accuracy,
        precision,
        recall,
        f1,
        auc
    ]

})

results_final["Valor"] = (
    results_final["Valor"]
    .round(4)
)

print("\n")
print("="*18)
print("RESULTADOS FINALES")
print("="*18)
print(results_final)

==================
RESULTADOS FINALES
==================
     Métrica   Valor
0   Accuracy  0.9290
1  Precision  0.9025
2     Recall  0.9191
3   F1-Score  0.9107
4    ROC-AUC  0.9723

In [33]:
# ======================= #
# 27. MATRIZ DE CONFUSIÓN #
# ======================= #

cm = confusion_matrix(
    y_test,
    y_pred_best
)

cm_df = pd.DataFrame(
    cm,
    index=["No Spam", "Spam"],
    columns=["Pred No Spam", "Pred Spam"]
)

fig = px.imshow(
    cm_df,
    text_auto=True,
    color_continuous_scale="Blues",
    title="Matriz de Confusión - Mejor Modelo"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5,
    height=500
)

fig.show()

# CURVA ROC #
fpr, tpr, thresholds = roc_curve(
    y_test,
    y_prob_best
)

fig = px.area(
    x=fpr,
    y=tpr,
    title=f"Curva ROC - AUC = {auc:.4f}"
)

fig.add_shape(
    type='line',
    line=dict(dash='dash'),
    x0=0,
    x1=1,
    y0=0,
    y1=1
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5,
    xaxis_title="False Positive Rate",
    yaxis_title="True Positive Rate",
    height=600
)

fig.show()

---
## **Análisis del Mejor Modelo**
---

In [34]:
# =========================== #
# 28. MEJORES HIPERPARÁMETROS #
# =========================== #

best_params = random_search.best_params_

print("\n")
print("="*70)
print("MEJORES HIPERPARÁMETROS")
print("="*70)

for key, value in best_params.items():
    print(f"{key}: {value}")

======================================================================
MEJORES HIPERPARÁMETROS
======================================================================
model__C: 11.594885940452201
model__class_weight: balanced
model__penalty: l2
model__solver: liblinear

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">


### **Interpretación de Hiperparámetros**

- **model__C = 11.5949**

Este hiperparámetro controla la fuerza de regularización.

$C$ grande → poca regularización
$C$ pequeño → mucha regularización

---

- **model__class_weight = balanced**

Este hiperparámetro corrige el problema de clases desbalanceadas. La clase minoritaria recibe mayor importancia.

---

- **model__penalty = l2**

La penalización L2 agrega una restricción cuadrática sobre los coeficientes, reduce coeficientes muy grandes.

---

- **model__solver = liblinear**

El solver es el algoritmo numérico usado para optimizar la regresión logística.

---

<div align="center">

**Interpretación Global del Modelo**

| Hiperparámetro | Interpretación |
|---|---|
| `C ≈ 11.59` | Baja regularización |
| `class_weight='balanced'` | Corrige desbalance |
| `penalty='l2'` | Reduce sobreajuste |
| `solver='liblinear'` | Solver eficiente para clasificación binaria |

</div>

</div>

---

In [35]:
# ================ #
# 29. MEJOR MODELO #
# ================ #

best_model = random_search.best_estimator_
best_model

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  []),
                                                 ('num', StandardScaler(),
                                                  ['make', 'address', 'all',
                                                   'num3d', 'our', 'over',
                                                   'remove', 'internet',
                                                   'order', 'mail', 'receive',
                                                   'will', 'people', 'report',
                                                   'addresses', 'free',
                                                   'business', 'email', 'you',
                                                   'credit', 'your', 'font',
                                                   'num000', 'money', 'hp',
                                                   'hpl', 'george', 'num650',
                                                   'lab', 'labs', ...])])),
                ('model',
                 LogisticRegression(C=np.float64(11.594885940452201),
                                    class_weight='balanced', max_iter=1000,
                                    random_state=123, solver='liblinear'))])

---
## **Importancia de las Variables**
---

In [36]:
# =================================== #
# 30. IMPORTANCIA VARIABLES POSITIVAS #
# =================================== #

# NOMBRES DE VARIABLES
feature_names = (
    best_model.named_steps["preprocessing"]
    .get_feature_names_out()
)

# COEFICIENTES
coeficients = (
    best_model.named_steps["model"]
    .coef_[0]
)

importance_df = pd.DataFrame({
    "Variable": feature_names,
    "Coeficiente": coeficients
})

# COEFICIENTES POSITIVOS
importance_positive = (
    importance_df[
        importance_df["Coeficiente"] > 0
    ]
    .sort_values(
        by="Coeficiente",
        ascending=False
    )
)

# TOP 20
top_positive = importance_positive.head(20)

fig = px.bar(
    top_positive,
    x="Coeficiente",
    y="Variable",
    orientation="h",
    text="Coeficiente",
    color="Coeficiente",
    color_continuous_scale="Reds",
    title="Top 20 Variables Positivas Más Asociadas al Spam"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5,
    height=700,
    coloraxis_showscale=False
)

# Mayor importancia arriba
fig.update_yaxes(
    categoryorder="total ascending"
)

fig.update_traces(
    texttemplate="%{text:.3f}",
    textposition="outside"
)

fig.show()

In [37]:
# =================================== #
# 31. IMPORTANCIA VARIABLES NEGATIVAS #
# =================================== #

feature_names = (
    best_model.named_steps["preprocessing"]
    .get_feature_names_out()
)

# COEFICIENTES
coeficients = (
    best_model.named_steps["model"]
    .coef_[0]
)

importance_df = pd.DataFrame({
    "Variable": feature_names,
    "Coeficiente": coeficients
})

# SOLO COEFICIENTES NEGATIVOS
importance_negative = (
    importance_df[
        importance_df["Coeficiente"] < 0
    ]
    .sort_values(
        by="Coeficiente",
        ascending=True
    )
)

top_negative = importance_negative.head(20)

fig = px.bar(
    top_negative,
    x="Coeficiente",
    y="Variable",
    orientation="h",
    text="Coeficiente",
    color="Coeficiente",
    color_continuous_scale="Blues",
    title="Top 20 Variables Negativas Más Asociadas a No Spam"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5,
    height=700,
    coloraxis_showscale=False
)

# Mayor importancia arriba
fig.update_yaxes(
    categoryorder="total descending"
)

fig.update_traces(
    texttemplate="%{text:.3f}",
    textposition="outside"
)

fig.show()

In [38]:
# ================================================ #
# 32. IMPORTANCIA DE VARIABLES REGRESIÓN LOGÍSTICA #
# ================================================ #

# OBTENER NOMBRES DE VARIABLES
feature_names = (
    best_model.named_steps["preprocessing"]
    .get_feature_names_out()
)

# COEFICIENTES DEL MODELO
coeficients = (
    best_model.named_steps["model"]
    .coef_[0]
)

importance_df = pd.DataFrame({
    "Variable": feature_names,
    "Coeficiente": coeficients,
    "Importancia": np.abs(coeficients)
})

importance_df = (
    importance_df
    .sort_values(
        by="Importancia",
        ascending=False
    )
)

# TOP VARIABLES
top_importance = importance_df.head(20)

print(top_importance)

# GRÁFICA
fig = px.bar(
    top_importance,
    x="Importancia",
    y="Variable",
    orientation="h",
    color="Coeficiente",
    color_continuous_scale="RdBu_r",
    title="Top 20 Variables Más Importantes"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5,
    height=700,
    yaxis=dict(
        categoryorder="total ascending"
    )
)

fig.show()

            Variable  Coeficiente  Importancia
26       num__george    -9.793223     9.793223
40           num__cs    -4.968173     4.968173
33       num__num415    -4.122731     4.122731
24           num__hp    -3.205784     3.205784
28          num__lab    -2.375971     2.375971
41      num__meeting    -1.904269     1.904269
31       num__num857     1.748025     1.748025
52   num__charDollar     1.271018     1.271018
3         num__num3d     1.180467     1.180467
45          num__edu    -1.169334     1.169334
43      num__project    -1.135381     1.135381
15         num__free     1.132999     1.132999
55  num__capitalLong     1.085864     1.085864
6        num__remove     0.931928     0.931928
34        num__num85    -0.893070     0.893070
19       num__credit     0.840250     0.840250
47   num__conference    -0.752694     0.752694
53     num__charHash     0.743283     0.743283
44           num__re    -0.710891     0.710891
22       num__num000     0.679631     0.679631

---
<div style="text-align: justify; line-height: 1.5; font-size: 18px;">  

### **Interpretación de Coeficientes**

---

En Regresión Logística, la “importancia” proviene de los coeficientes:

$$\log\left(\frac{p(x)}{1-p(x)}\right) = \beta_0 + \beta_1x_1 + \ldots + \beta_px_p$$

---

- **Coeficiente positivo :** $\beta_i>0$

La variable aumenta la probabilidad de spam.

---

- **Coeficiente negativo :** $\beta_i<0$

La variable reduce la probabilidad de spam.

---

- **Mientras más grande :** $∣\beta_i∣$

Más influencia tiene la variable sobre la clasificación.

---

</div>

## **Serialización del Mejor Modelo**

---

In [39]:
# ======================================== #
# 33. CARPETA DONDE SE GUARDARÁ EL .joblib #
# ======================================== #
ruta = Path("/Users/duvancatano/Documents/Estadistica_Analitica_Datos_UPTC_2026-2/models")

# CREAR CARPETA SINO EXISTE #
ruta.mkdir(parents=True, exist_ok=True)

In [40]:
# ============================================== #
# 34. MODELO FINAL CON TODO EL CONJUNTO DE DATOS #
# ============================================== #

final_model = Pipeline([
    ("preprocessing", preprocessor),
    ("model",
        LogisticRegression(
            C=11.594885940452201,
            class_weight="balanced",
            penalty="l2",
            solver="liblinear",
            max_iter=1000,
            random_state=123
        )
    )
])

# Entrenamiento final
final_model.fit(X, y)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  []),
                                                 ('num', StandardScaler(),
                                                  ['make', 'address', 'all',
                                                   'num3d', 'our', 'over',
                                                   'remove', 'internet',
                                                   'order', 'mail', 'receive',
                                                   'will', 'people', 'report',
                                                   'addresses', 'free',
                                                   'business', 'email', 'you',
                                                   'credit', 'your', 'font',
                                                   'num000', 'money', 'hp',
                                                   'hpl', 'george', 'num650',
                                                   'lab', 'labs', ...])])),
                ('model',
                 LogisticRegression(C=11.594885940452201,
                                    class_weight='balanced', max_iter=1000,
                                    random_state=123, solver='liblinear'))])

In [41]:
# ======================== #
# 35. GUARDAR MODELO FINAL #
# ======================== #

joblib.dump(final_model, ruta / "model_logistic_regression.joblib")

['/Users/duvancatano/Documents/Estadistica_Analitica_Datos_UPTC_2026-2/models/model_logistic_regression.joblib']

In [42]:
# ===================== #
# 37. GUARDAR VARIABLES #
# ===================== #

joblib.dump(X.columns.tolist(), ruta / "features_logistic_regression.joblib")

['/Users/duvancatano/Documents/Estadistica_Analitica_Datos_UPTC_2026-2/models/features_logistic_regression.joblib']

---

# 🎬 **¡FIN!**

---

<div style="text-align: justify; line-height: 1.5; font-size: 18px;">    </div>